---
title: "Import_Map"
author:
- Sylwia Sliwinska-Wilczewska
- Douglas A. Campbell
date: "`r format(Sys.Date())`"
output:
bookdown::html_document2:
    code_folding: show
    keep_md: yes
    toc: TRUE
    toc_float: TRUE
    toc_depth: 6
    fig_caption: yes
bibliography: BalticPhotoperiod.bib
csl: plos-one.csl
editor_options: 
  markdown: 
    wrap: 72
---

# Set Chunk Options

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
knitr::opts_chunk$set(fig.path='Figs/')
```

# Introduction


# Load Libraries and set Project Variables

```{r load libraries} 
library(tidyverse)
#library(lubridate)
#library(stringr)
library(broom)
#library(knitr)
library(OneR)
library(zoo)
library(ggpubr)
library(data.table)
# library(googledrive)
# library(googlesheets4)
library(ggspectra)
library(photobiologyWavebands)
library(photobiology)
library(ggforce) #ellipse
library("patchwork") # merging plots

```

```{r set project variables}
Project <- "prochlorococcus_O2"

FigPath <- file.path("..", "Output", "Figures")
#FigRdsPath <- file.path("..", "Output", "FiguresRds")
#TableRdsPath <- file.path("..", "Output", "TablesRDS")
```

----------------------------------------Create map ----------------------------------------------

# Create map
https://www.geeksforgeeks.org/how-to-make-world-map-with-ggplot2-in-r/

```{r}
world_coordinates <- map_data("world") 
world_coordinates$facetsTropicFull <- 'Season:~All~year~~Hours~of~daylight:~12~~Oxygen:~Full'
world_coordinates$facetsSpringFull <- 'Season:~Spring/Fall~~~~~~~~~~~~~~Oxygen:~Full'
world_coordinates$facetsSummerFull <- 'Season:~Summer~~~~~~~~~~~~~~Oxygen:~Full'
world_coordinates$facetsWinterFull <- 'Season:~Winter~~~~~~~~~~~~~~Oxygen:~Full'

world_coordinates$facetsTropicOMZ <- 'Season:~All~year~~~~~~~~~~~~~~Oxygen:~OMZ'
world_coordinates$facetsSpringOMZ <- 'Season:~Spring/Fall~~~~~~~~~~~~~~Oxygen:~OMZ'
world_coordinates$facetsSummerOMZ <- 'Season:~Summer~~~~~~~~~~~~~~Oxygen:~OMZ'
world_coordinates$facetsWinterOMZ <- 'Season:~Winter~~~~~~~~~~~~~~Oxygen:~OMZ'

```


```{r create GrowthCurve plot, fig.height = 4, fig.width = 6, warning = FALSE}
data_textA <- data.frame(label = c('A'))

d=data.frame(x1=c(-Inf), x2=c(Inf), y1=c(35), y2=c(55))
d2=data.frame(x1=c(-Inf), x2=c(Inf), y1=c(-35), y2=c(-55))
d3=data.frame(x1=c(-Inf), x2=c(Inf), y1=c(-Inf), y2=c(Inf))
d4=data.frame(x1=c(-Inf), x2=c(Inf), y1=c(-15), y2=c(15))
d5=data.frame(x1=c(-Inf), x2=c(Inf), y1=c(-40), y2=c(40))

data_textTropicFull <- data.frame(label = c('Season:~All~year~~~~~~~~Daylight:~12~h~~~~~~~~Oxygen:~Full'))
TropicFull<-ggplot() + 
  geom_rect(data=d5, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "transparent", color="darkgreen", linetype = "dashed", alpha=1, size = 1) +
  geom_rect(data=d3, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "lightskyblue1", color="lightskyblue3", alpha=0.5) +
  geom_rect(data=d4, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "khaki1", color="khaki2", alpha=0.8) +
  geom_map(data = world_coordinates, map = world_coordinates, aes(long, lat, map_id = region), color = "white", fill = "gray50", size = 0.2) +

  geom_text(data=data_textTropicFull, aes(x=0, y=110, label=label), size=4.5, parse=TRUE) +
  scale_y_continuous(breaks=seq(-90, 90, by = 45)) +
  coord_cartesian(ylim = c(-90, 120)) +
  labs(y = "Latitude", x = "Longitude") +
  #ggh4x::facet_nested(cols = vars(facetsTropicFull), labeller = label_parsed) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        axis.text = element_text(size=14),
        axis.title = element_text(size=18),
        strip.background = element_rect(fill="white"),
        strip.text = element_text(size=14),
        axis.title.y = element_text(margin=margin(r=10)),
        #axis.title.x = element_text(margin=margin(t=10)),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.background = element_rect(fill="transparent"),
        legend.position = c(0.12,0.76),
        legend.key.height= unit(0.005, 'cm'),
        legend.spacing.x = unit(0.01, 'cm'),
        legend.text = element_text(size=14))
TropicFull

data_textSpringFull <- data.frame(label = c('Season:~Spring/Fall~~~~~~~~Daylight:~12~h~~~~~~~~Oxygen:~Full'))
SpringFull<-ggplot() + 
  geom_rect(data=d3, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "lightskyblue1", color="lightskyblue3", alpha=0.5) +
  geom_rect(data=d, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "khaki1", color="khaki2", alpha=0.8) +
  geom_rect(data=d2, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "khaki1", color="khaki2", alpha=0.8) +
  geom_map(data = world_coordinates, map = world_coordinates, aes(long, lat, map_id = region), color = "white", fill = "gray50", size = 0.2) +
  geom_text(data=data_textSpringFull, aes(x=0, y=110, label=label), size=4.5, parse=TRUE) +
  scale_y_continuous(breaks=seq(-90, 90, by = 45)) +
  coord_cartesian(ylim = c(-90, 120)) +
  labs(y = "Latitude", x = "Longitude") +
  #ggh4x::facet_nested(cols = vars(facetsSpringFull), labeller = label_parsed) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        axis.text = element_text(size=14),
        axis.title = element_text(size=18),
        strip.background = element_rect(fill="white"),
        strip.text = element_text(size=14),
        axis.title.y = element_text(margin=margin(r=10)),
        #axis.title.x = element_text(margin=margin(t=10)),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.background = element_rect(fill="transparent"),
        legend.position = c(0.12,0.76),
        legend.key.height= unit(0.005, 'cm'),
        legend.spacing.x = unit(0.01, 'cm'),
        legend.text = element_text(size=14))
SpringFull

data_textSummerFull <- data.frame(label = c('Season:~Summer~~~~~~~~Daylight:~16~h~~~~~~~~Oxygen:~Full'))
SummerFull<-ggplot() + 
  geom_rect(data=d3, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "lightskyblue1", color="lightskyblue3", alpha=0.5) +
  geom_rect(data=d, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "khaki1", color="khaki2", alpha=0.8) +
  geom_rect(data=d2, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "khaki1", color="khaki2", alpha=0.8) +
  geom_map(data = world_coordinates, map = world_coordinates, aes(long, lat, map_id = region), color = "white", fill = "gray50", size = 0.2) +
  geom_text(data=data_textSummerFull, aes(x=0, y=110, label=label), size=4.5, parse=TRUE) +
  scale_y_continuous(breaks=seq(-90, 90, by = 45)) +
  coord_cartesian(ylim = c(-90, 120)) +
  labs(y = "Latitude", x = "Longitude") +
  #ggh4x::facet_nested(cols = vars(facetsSummerFull), labeller = label_parsed) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        axis.text = element_text(size=14),
        axis.title = element_text(size=18),
        strip.background = element_rect(fill="white"),
        strip.text = element_text(size=14),
        axis.title.y = element_text(margin=margin(r=10)),
        #axis.title.x = element_text(margin=margin(t=10)),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.background = element_rect(fill="transparent"),
        legend.position = c(0.12,0.76),
        legend.key.height= unit(0.005, 'cm'),
        legend.spacing.x = unit(0.01, 'cm'),
        legend.text = element_text(size=14))
SummerFull

data_textWinterFull <- data.frame(label = c('Season:~Summer~~~~~~~~Daylight:~8~h~~~~~~~~Oxygen:~Full'))
WinterFull<-ggplot() + 
  geom_rect(data=d3, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "lightskyblue1", color="lightskyblue3", alpha=0.5) +
  geom_rect(data=d, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "khaki1", color="khaki2", alpha=0.8) +
  geom_rect(data=d2, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "khaki1", color="khaki2", alpha=0.8) +
  geom_map(data = world_coordinates, map = world_coordinates, aes(long, lat, map_id = region), color = "white", fill = "gray50", size = 0.2) +
  geom_text(data=data_textWinterFull, aes(x=0, y=110, label=label), size=4.5, parse=TRUE) +
  scale_y_continuous(breaks=seq(-90, 90, by = 45)) +
  coord_cartesian(ylim = c(-90, 120)) +
  labs(y = "Latitude", x = "Longitude") +
  #ggh4x::facet_nested(cols = vars(facetsWinterFull), labeller = label_parsed) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        axis.text = element_text(size=14),
        axis.title = element_text(size=18),
        strip.background = element_rect(fill="white"),
        strip.text = element_text(size=14),
        axis.title.y = element_text(margin=margin(r=10)),
        axis.title.x = element_text(margin=margin(t=10)),
        #axis.title.x = element_blank(),
        legend.background = element_rect(fill="transparent"),
        legend.position = c(0.12,0.76),
        legend.key.height= unit(0.005, 'cm'),
        legend.spacing.x = unit(0.01, 'cm'),
        legend.text = element_text(size=14))
WinterFull

```


```{r, warning = FALSE, fig.height = 12, fig.width = 6}
Full<- (TropicFull/SpringFull/SummerFull/WinterFull)
Full                         
```

```{r create map omz plot, fig.height = 4, fig.width = 6, warning = FALSE}
data_textA <- data.frame(label = c('A'))

d=data.frame(x1=c(-Inf), x2=c(Inf), y1=c(35), y2=c(55))
d2=data.frame(x1=c(-Inf), x2=c(Inf), y1=c(-35), y2=c(-55))
d3=data.frame(x1=c(-Inf), x2=c(Inf), y1=c(-Inf), y2=c(Inf))
d4=data.frame(x1=c(-Inf), x2=c(Inf), y1=c(-15), y2=c(15))

data_textTropicOMZ <- data.frame(label = c('Season:~All~year~~~~~~~~Daylight:~12~h~~~~~~~~Oxygen:~OMZ'))
TropicOMZ<-ggplot() + 
  geom_rect(data=d5, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "transparent", color="darkgreen", linetype = "dashed", alpha=0.9, size = 1) +
  geom_rect(data=d3, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "lightskyblue1", color="lightskyblue3", alpha=0.5) +
  geom_rect(data=d4, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "khaki1", color="khaki2", alpha=0.8) +
  geom_map(data = world_coordinates, map = world_coordinates, aes(long, lat, map_id = region), color = "white", fill = "gray50", size = 0.2) +

  geom_text(data=data_textTropicOMZ, aes(x=0, y=110, label=label), size=4.5, parse=TRUE) +
  scale_y_continuous(breaks=seq(-90, 90, by = 45)) +
  coord_cartesian(ylim = c(-90, 120)) +
  labs(y = "Latitude", x = "Longitude") +
  #ggh4x::facet_nested(cols = vars(facetsTropicOMZ), labeller = label_parsed) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        axis.text = element_text(size=14),
        axis.title = element_text(size=18),
        strip.background = element_rect(fill="white"),
        strip.text = element_text(size=14),
        axis.title.y = element_text(margin=margin(r=10)),
        #axis.title.x = element_text(margin=margin(t=10)),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.background = element_rect(fill="transparent"),
        legend.position = c(0.12,0.76),
        legend.key.height= unit(0.005, 'cm'),
        legend.spacing.x = unit(0.01, 'cm'),
        legend.text = element_text(size=14))
TropicOMZ


data_textSpringOMZ <- data.frame(label = c('Season:~Spring/Fall~~~~~~~~Daylight:~12~h~~~~~~~~Oxygen:~OMZ'))
SpringOMZ<-ggplot() + 
  geom_rect(data=d3, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "lightskyblue1", color="lightskyblue3", alpha=0.5) +
  geom_rect(data=d, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "khaki1", color="khaki2", alpha=0.8) +
  geom_rect(data=d2, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "khaki1", color="khaki2", alpha=0.8) +
  geom_map(data = world_coordinates, map = world_coordinates, aes(long, lat, map_id = region), color = "white", fill = "gray50", size = 0.2) +
  geom_text(data=data_textSpringOMZ, aes(x=0, y=110, label=label), size=4.5, parse=TRUE) +
  scale_y_continuous(breaks=seq(-90, 90, by = 45)) +
  coord_cartesian(ylim = c(-90, 120)) +
  labs(y = "Latitude", x = "Longitude") +
  #ggh4x::facet_nested(cols = vars(facetsSpringOMZ), labeller = label_parsed) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        axis.text = element_text(size=14),
        axis.title = element_text(size=18),
        strip.background = element_rect(fill="white"),
        strip.text = element_text(size=14),
        axis.title.y = element_text(margin=margin(r=10)),
        #axis.title.x = element_text(margin=margin(t=10)),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.background = element_rect(fill="transparent"),
        legend.position = c(0.12,0.76),
        legend.key.height= unit(0.005, 'cm'),
        legend.spacing.x = unit(0.01, 'cm'),
        legend.text = element_text(size=14))
SpringOMZ


data_textSummerOMZ <- data.frame(label = c('Season:~Summer~~~~~~~~Daylight:~16~h~~~~~~~~Oxygen:~OMZ'))
SummerOMZ<-ggplot() + 
  geom_rect(data=d3, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "lightskyblue1", color="lightskyblue3", alpha=0.5) +
  geom_rect(data=d, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "khaki1", color="khaki2", alpha=0.8) +
  geom_rect(data=d2, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "khaki1", color="khaki2", alpha=0.8) +
  geom_map(data = world_coordinates, map = world_coordinates, aes(long, lat, map_id = region), color = "white", fill = "gray50", size = 0.2) +
  geom_text(data=data_textSummerOMZ, aes(x=0, y=110, label=label), size=4.5, parse=TRUE) +
  scale_y_continuous(breaks=seq(-90, 90, by = 45)) +
  coord_cartesian(ylim = c(-90, 120)) +
  labs(y = "Latitude", x = "Longitude") +
  #ggh4x::facet_nested(cols = vars(facetsSummerOMZ), labeller = label_parsed) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        axis.text = element_text(size=14),
        axis.title = element_text(size=18),
        strip.background = element_rect(fill="white"),
        strip.text = element_text(size=14),
        axis.title.y = element_text(margin=margin(r=10)),
        #axis.title.x = element_text(margin=margin(t=10)),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.background = element_rect(fill="transparent"),
        legend.position = c(0.12,0.76),
        legend.key.height= unit(0.005, 'cm'),
        legend.spacing.x = unit(0.01, 'cm'),
        legend.text = element_text(size=14))
SummerOMZ

data_textWinterOMZ <- data.frame(label = c('Season:~Summer~~~~~~~~Daylight:~8~h~~~~~~~~Oxygen:~OMZ'))
WinterOMZ<-ggplot() + 
  geom_rect(data=d3, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "lightskyblue1", color="lightskyblue3", alpha=0.5) +
  geom_rect(data=d, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "khaki1", color="khaki2", alpha=0.8) +
  geom_rect(data=d2, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "khaki1", color="khaki2", alpha=0.8) +
  geom_map(data = world_coordinates, map = world_coordinates, aes(long, lat, map_id = region), color = "white", fill = "gray50", size = 0.2) +
  geom_text(data=data_textWinterOMZ, aes(x=0, y=110, label=label), size=4.5, parse=TRUE) +
  scale_y_continuous(breaks=seq(-90, 90, by = 45)) +
  coord_cartesian(ylim = c(-90, 120)) +
  labs(y = "Latitude", x = "Longitude") +
  #ggh4x::facet_nested(cols = vars(facetsWinterOMZ), labeller = label_parsed) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        axis.text = element_text(size=14),
        axis.title = element_text(size=18),
        strip.background = element_rect(fill="white"),
        strip.text = element_text(size=14),
        axis.title.y = element_text(margin=margin(r=10)),
        axis.title.x = element_text(margin=margin(t=10)),
        #axis.title.x = element_blank(),
        legend.background = element_rect(fill="transparent"),
        legend.position = c(0.12,0.76),
        legend.key.height= unit(0.005, 'cm'),
        legend.spacing.x = unit(0.01, 'cm'),
        legend.text = element_text(size=14))
WinterOMZ

```


```{r, warning = FALSE, fig.height = 12, fig.width = 6}
OMZ<- (TropicOMZ/SpringOMZ/SummerOMZ/WinterOMZ)
OMZ                         
```


https://sape.inf.usi.ch/quick-reference/ggplot2/geom_polygon
```{r}
world_coordinatesRainbow <- map_data("world")
world_coordinatesRainbow$nm <- c(400, 700)

data_textTropicFullRainbowSurface <- data.frame(label = c('Near~surface~(180~µE~","~8~h):~Clade~HLI'))
data_textTropicFullRainbowDeep <- data.frame(label = c('Deep~(30~µE~","~8~h):~Clades~HLI~","~LLII/III~","~LLIV'))
d=data.frame(x=c(400,700,700), y=c(100,100,200), t=c('a', 'a', 'a'), r=c(1,2,3))
TropicFullRainbow<-ggplot() +
  stat_wl_strip(aes(x = nm), ymin = 100, ymax = 200, alpha = 0.5, world_coordinatesRainbow) +
  scale_fill_identity() +
  geom_polygon(data=d, mapping=aes(x=x, y=y, group=t), fill = "white", show.legend = F) +
  geom_ellipse(aes(x0 = 555, y0 = 143, a = 164, b = 28, angle = pi / 10), fill = "white", colour = "white") +
  coord_fixed() +
  scale_y_continuous(breaks=seq(100, 200, by = 50)) +
  coord_cartesian(ylim = c(80, 220)) +
  geom_text(data=data_textTropicFullRainbowSurface, aes(x=510, y=215, label=label), size=4.5, parse=TRUE) +
  geom_text(data=data_textTropicFullRainbowDeep, aes(x=530, y=90, label=label), size=4.5, parse=TRUE) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        axis.text = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank(),
        strip.background = element_rect(fill="white"),
        strip.text = element_text(size=14),
        legend.background = element_rect(fill="transparent"),
        legend.position = c(0.12,0.76),
        legend.text = element_text(size=14))
TropicFullRainbow


data_textSpringFullRainbowSurface <- data.frame(label = c('Near~surface~(180~µE~","~8~h):~Clade~HLI'))
data_textSpringFullRainbowDeep <- data.frame(label = c('Deep~(30~µE~","~8~h):~Clades~HLI~","~LLII/III~","~LLIV'))
d=data.frame(x=c(400,700,700), y=c(100,100,200), t=c('a', 'a', 'a'), r=c(1,2,3))
SpringFullRainbow<-ggplot() +
  stat_wl_strip(aes(x = nm), ymin = 100, ymax = 200, alpha = 0.5, world_coordinatesRainbow) +
  scale_fill_identity() +
  geom_polygon(data=d, mapping=aes(x=x, y=y, group=t), fill = "white", show.legend = F) +
  geom_ellipse(aes(x0 = 555, y0 = 143, a = 164, b = 28, angle = pi / 10), fill = "white", colour = "white") +
  coord_fixed() +
  scale_y_continuous(breaks=seq(100, 200, by = 50)) +
  coord_cartesian(ylim = c(80, 220)) +
  geom_text(data=data_textSpringFullRainbowSurface, aes(x=510, y=215, label=label), size=4.5, parse=TRUE) +
  geom_text(data=data_textSpringFullRainbowDeep, aes(x=530, y=90, label=label), size=4.5, parse=TRUE) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        axis.text = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank(),
        strip.background = element_rect(fill="white"),
        strip.text = element_text(size=14),
        legend.background = element_rect(fill="transparent"),
        legend.position = c(0.12,0.76),
        legend.text = element_text(size=14))
SpringFullRainbow

data_textSummerFullRainbowSurface <- data.frame(label = c('Near~surface~(180~µE~","~12~h):~Clade~HLI'))
data_textSummerFullRainbowDeep <- data.frame(label = c('Deep~(30~µE~","~12~h):~Clades~HLI~","~LLII/III~","~LLIV'))
d=data.frame(x=c(400,700,700), y=c(100,100,200), t=c('a', 'a', 'a'), r=c(1,2,3))
SummerFullRainbow<-ggplot() +
  stat_wl_strip(aes(x = nm), ymin = 100, ymax = 200, alpha = 0.5, world_coordinatesRainbow) +
  scale_fill_identity() +
  geom_polygon(data=d, mapping=aes(x=x, y=y, group=t), fill = "white", show.legend = F) +
  geom_ellipse(aes(x0 = 555, y0 = 143, a = 164, b = 28, angle = pi / 10), fill = "white", colour = "white") +
  coord_fixed() +
  scale_y_continuous(breaks=seq(100, 200, by = 50)) +
  coord_cartesian(ylim = c(80, 220)) +
  geom_text(data=data_textSummerFullRainbowSurface, aes(x=510, y=215, label=label), size=4.5, parse=TRUE) +
  geom_text(data=data_textSummerFullRainbowDeep, aes(x=530, y=90, label=label), size=4.5, parse=TRUE) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        axis.text = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank(),
        strip.background = element_rect(fill="white"),
        strip.text = element_text(size=14),
        legend.background = element_rect(fill="transparent"),
        legend.position = c(0.12,0.76),
        legend.text = element_text(size=14))
SummerFullRainbow


data_textWinterFullRainbowSurface <- data.frame(label = c('Near~surface~(180~µE~","~4~h)'))
data_textWinterFullRainbowDeep <- data.frame(label = c('Deep~(30~µE~","~4~h):~Clade~LLIV'))
d=data.frame(x=c(400,700,700), y=c(100,100,200), t=c('a', 'a', 'a'), r=c(1,2,3))
WinterFullRainbow<-ggplot() +
  stat_wl_strip(aes(x = nm), ymin = 100, ymax = 200, alpha = 0.5, world_coordinatesRainbow) +
  scale_fill_identity() +
  geom_polygon(data=d, mapping=aes(x=x, y=y, group=t), fill = "white", show.legend = F) +
  geom_ellipse(aes(x0 = 555, y0 = 143, a = 164, b = 28, angle = pi / 10), fill = "white", colour = "white") +
  coord_fixed() +
  scale_y_continuous(breaks=seq(100, 200, by = 50)) +
  coord_cartesian(ylim = c(80, 220)) +
  geom_text(data=data_textWinterFullRainbowSurface, aes(x=480, y=215, label=label), size=4.5, parse=TRUE) +
  geom_text(data=data_textWinterFullRainbowDeep, aes(x=485, y=90, label=label), size=4.5, parse=TRUE) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        axis.text = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank(),
        strip.background = element_rect(fill="white"),
        strip.text = element_text(size=14),
        legend.background = element_rect(fill="transparent"),
        legend.position = c(0.12,0.76),
        legend.text = element_text(size=14))
WinterFullRainbow
```
```{r, warning = FALSE, fig.height = 12, fig.width = 6}
FullRainbow<- (TropicFullRainbow/SpringFullRainbow/SummerFullRainbow/WinterFullRainbow)
FullRainbow                         
```

```{r}
data_textTropicOMZRainbowSurface <- data.frame(label = c('Near~surface~(180~µE~","~8~h):~Clades~HLI~","~LLII/III~","~LLIV'))
data_textTropicOMZRainbowDeep <- data.frame(label = c('Deep~(30~µE~","~8~h):~Clades~HLI~","~LLII/III~","~LLIV'))
d=data.frame(x=c(400,700,700), y=c(100,100,200), t=c('a', 'a', 'a'), r=c(1,2,3))
TropicOMZRainbow<-ggplot() +
  stat_wl_strip(aes(x = nm), ymin = 100, ymax = 200, alpha = 0.5, world_coordinatesRainbow) +
  scale_fill_identity() +
  geom_polygon(data=d, mapping=aes(x=x, y=y, group=t), fill = "white", show.legend = F) +
  geom_ellipse(aes(x0 = 555, y0 = 143, a = 164, b = 28, angle = pi / 10), fill = "white", colour = "white") +
  coord_fixed() +
  scale_y_continuous(breaks=seq(100, 200, by = 50)) +
  coord_cartesian(ylim = c(80, 220)) +
  geom_text(data=data_textTropicOMZRainbowSurface, aes(x=555, y=215, label=label), size=4.5, parse=TRUE) +
  geom_text(data=data_textTropicOMZRainbowDeep, aes(x=530, y=90, label=label), size=4.5, parse=TRUE) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        axis.text = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank(),
        strip.background = element_rect(fill="white"),
        strip.text = element_text(size=14),
        legend.background = element_rect(fill="transparent"),
        legend.position = c(0.12,0.76),
        legend.text = element_text(size=14))
TropicOMZRainbow

data_textSpringOMZRainbowSurface <- data.frame(label = c('Near~surface~(180~µE~","~8~h):~Clades~HLI~","~LLII/III~","~LLIV'))
data_textSpringOMZRainbowDeep <- data.frame(label = c('Deep~(30~µE~","~8~h):~Clades~HLI~","~LLII/III~","~LLIV'))
d=data.frame(x=c(400,700,700), y=c(100,100,200), t=c('a', 'a', 'a'), r=c(1,2,3))
SpringOMZRainbow<-ggplot() +
  stat_wl_strip(aes(x = nm), ymin = 100, ymax = 200, alpha = 0.5, world_coordinatesRainbow) +
  scale_fill_identity() +
  geom_polygon(data=d, mapping=aes(x=x, y=y, group=t), fill = "white", show.legend = F) +
  geom_ellipse(aes(x0 = 555, y0 = 143, a = 164, b = 28, angle = pi / 10), fill = "white", colour = "white") +
  coord_fixed() +
  scale_y_continuous(breaks=seq(100, 200, by = 50)) +
  coord_cartesian(ylim = c(80, 220)) +
  geom_text(data=data_textSpringOMZRainbowSurface, aes(x=555, y=215, label=label), size=4.5, parse=TRUE) +
  geom_text(data=data_textSpringOMZRainbowDeep, aes(x=530, y=90, label=label), size=4.5, parse=TRUE) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        axis.text = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank(),
        strip.background = element_rect(fill="white"),
        strip.text = element_text(size=14),
        legend.background = element_rect(fill="transparent"),
        legend.position = c(0.12,0.76),
        legend.text = element_text(size=14))
SpringOMZRainbow

data_textSummerOMZRainbowSurface <- data.frame(label = c('Near~surface~(180~µE~","~12~h):~Clades~HLI~","~LLIV'))
data_textSummerOMZRainbowDeep <- data.frame(label = c('Deep~(30~µE~","~12~h):~Clades~HLI~","~LLII/III~","~LLIV'))
d=data.frame(x=c(400,700,700), y=c(100,100,200), t=c('a', 'a', 'a'), r=c(1,2,3))
SummerOMZRainbow<-ggplot() +
  stat_wl_strip(aes(x = nm), ymin = 100, ymax = 200, alpha = 0.5, world_coordinatesRainbow) +
  scale_fill_identity() +
  geom_polygon(data=d, mapping=aes(x=x, y=y, group=t), fill = "white", show.legend = F) +
  geom_ellipse(aes(x0 = 555, y0 = 143, a = 164, b = 28, angle = pi / 10), fill = "white", colour = "white") +
  coord_fixed() +
  scale_y_continuous(breaks=seq(100, 200, by = 50)) +
  coord_cartesian(ylim = c(80, 220)) +
  geom_text(data=data_textSummerOMZRainbowSurface, aes(x=535, y=215, label=label), size=4.5, parse=TRUE) +
  geom_text(data=data_textSummerOMZRainbowDeep, aes(x=535, y=90, label=label), size=4.5, parse=TRUE) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        axis.text = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank(),
        strip.background = element_rect(fill="white"),
        strip.text = element_text(size=14),
        legend.background = element_rect(fill="transparent"),
        legend.position = c(0.12,0.76),
        legend.text = element_text(size=14))
SummerOMZRainbow


data_textWinterOMZRainbowSurface <- data.frame(label = c('Near~surface~(180~µE~","~4~h):~Clade~LLIV'))
data_textWinterOMZRainbowDeep <- data.frame(label = c('Deep~(30~µE~","~4~h):~Clades~LLII/III~","~LLIV'))
d=data.frame(x=c(400,700,700), y=c(100,100,200), t=c('a', 'a', 'a'), r=c(1,2,3))
WinterOMZRainbow<-ggplot() +
  stat_wl_strip(aes(x = nm), ymin = 100, ymax = 200, alpha = 0.5, world_coordinatesRainbow) +
  scale_fill_identity() +
  geom_polygon(data=d, mapping=aes(x=x, y=y, group=t), fill = "white", show.legend = F) +
  geom_ellipse(aes(x0 = 555, y0 = 143, a = 164, b = 28, angle = pi / 10), fill = "white", colour = "white") +
  coord_fixed() +
  scale_y_continuous(breaks=seq(100, 200, by = 50)) +
  coord_cartesian(ylim = c(80, 220)) +
  geom_text(data=data_textWinterOMZRainbowSurface, aes(x=510, y=215, label=label), size=4.5, parse=TRUE) +
  geom_text(data=data_textWinterOMZRainbowDeep, aes(x=510, y=90, label=label), size=4.5, parse=TRUE) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        axis.text = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank(),
        strip.background = element_rect(fill="white"),
        strip.text = element_text(size=14),
        legend.background = element_rect(fill="transparent"),
        legend.position = c(0.12,0.76),
        legend.text = element_text(size=14))
WinterOMZRainbow
```
```{r, warning = FALSE, fig.height = 12, fig.width = 6}
OMZRainbow<- (TropicOMZRainbow/SpringOMZRainbow/SummerOMZRainbow/WinterOMZRainbow)
OMZRainbow                         
```


```{r, warning = FALSE, fig.height = 16, fig.width = 22}
# MapCombo<-((TropicFull+TropicFullRainbow)+(TropicOMZ+TropicOMZRainbow))/((SpringFull+SpringFullRainbow)+(SpringOMZ+SpringOMZRainbow))/((SummerFull+SummerFullRainbow)+(SummerOMZ+SummerOMZRainbow))/((WinterFull+WinterFullRainbow)+(WinterOMZ+WinterOMZRainbow))
# MapCombo                          
```

```{r, warning = FALSE, fig.height = 16, fig.width = 22}
MapCombo1<-((TropicFull+TropicFullRainbow))/((SpringFull+SpringFullRainbow))/((SummerFull+SummerFullRainbow))/((WinterFull+WinterFullRainbow))
MapCombo1                         
```

```{r, warning = FALSE, fig.height = 16, fig.width = 22}
MapCombo2<-((TropicOMZ+TropicOMZRainbow))/((SpringOMZ+SpringOMZRainbow))/((SummerOMZ+SummerOMZRainbow))/((WinterOMZ+WinterOMZRainbow))
MapCombo2                          
```


```{r, warning = FALSE, fig.height = 16, fig.width = 22}
library(ggpubr)
ggarrange(MapCombo1, MapCombo2, 
          ncol = 2, nrow = 1)
```

```{r save plot}
ggsave(file = file.path(FigPath, paste("MapComboPro_2",".png",sep = "")), height=16, width= 22,  dpi = 300, limitsize = TRUE)
```


# Save rds for further analysis

```{r save rds}
# saveRDS(object = CultureCatalog, file = file.path("..", "Data", "ImportedData", "ImportedMetaData", "CultureCatalog.Rds"), compress = "xz")
```

https://ggforce.data-imaginist.com/reference/geom_ellipse.html
elipse

```{r}

# ggplot() +
#   geom_ellipse(aes(x0 = 550, y0 = 150, a = 150, b = 50, angle = pi / 4)) +
#   coord_fixed()
```


```{r}
# d=data.frame(x=c(400,700,700), y=c(100,100,200), t=c('a', 'a', 'a'), r=c(1,2,3))
# ggplot() +
#   stat_wl_strip(aes(x = nm), ymin = 100, ymax = 200, alpha = 0.5, world_coordinatesRainbow) +
#   scale_fill_identity() +
#   geom_polygon(data=d, mapping=aes(x=x, y=y, group=t), fill = "white", show.legend = F) +
#   scale_y_continuous(breaks=seq(100, 200, by = 50)) +
#   coord_cartesian(ylim = c(80, 220)) +
#   theme_bw() +
#   geom_ellipse(aes(x0 = 555, y0 = 143, a = 164, b = 28, angle = pi / 10), fill = "white", colour = "white") +
#   coord_fixed()
```

```{r}
# library(ggthemes)
# library(mapproj)
# world_map = map_data("world") %>% 
#   filter(! long > 180)
# 
# countries = world_map %>% 
#   distinct(region) %>% 
#   rowid_to_column()
# 
# countries %>% 
#   ggplot(aes(map_id = region), fill = "midnightblue") +
#   geom_map(map = world_map) +
#   expand_limits(x = world_map$long, y = world_map$lat) +
#   coord_map("moll") 
#   #theme_map()
# 
# 
# 
# 
# world_map = map_data("world") %>% 
#   filter(! long > 180)
#   
# distinct(world_map, region) %>% 
#   ggplot(aes(map_id = region), fill = "midnightblue") +
#   geom_map(map = world_map) +
#   expand_limits(x = world_map$long, y = world_map$lat) +
#   coord_map("moll") 
#   #coord_equal() 
```




