---
title: "Import_Map"
author:
- Sylwia Sliwinska-Wilczewska
- Douglas A. Campbell
date: "`r format(Sys.Date())`"
output:
bookdown::html_document2:
    code_folding: show
    keep_md: yes
    toc: TRUE
    toc_float: TRUE
    toc_depth: 6
    fig_caption: yes
bibliography: Manuscript_O2.bib
csl: plos-one.csl
editor_options: 
  markdown: 
    wrap: 72
---

# Set Chunk Options

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
knitr::opts_chunk$set(fig.path='Figs/')
```

# Introduction


# Load Libraries and set Project Variables

```{r load libraries} 
library(tidyverse)
library(broom)
library(OneR)
library(zoo)
library(ggpubr)
library(data.table)
library(ggspectra)
library(photobiologyWavebands)
library(photobiology)
library(ggforce) #ellipse
library("cowplot")
library("patchwork") # merging plots
library(grid) # for making one strip bigger - grid.draw

```

```{r set project variables}
Project <- "prochlorococcus_O2"

FigPath <- file.path("..", "Output", "Figures")
```

```{r read photoperiod depth data}
PhotoperiodDepth <- readRDS(file = file.path("..", "Data", "ProcessedData", "DepthPhotoperiodTableFilter.Rds"))


PhotoperiodDepthOMZ <- PhotoperiodDepth |>
  select(-c(ToD, DepthPARabs, DepthPARSine, DepthPARabsNA, Photicperiod:PhoticperiodSineSatPAR_h)) |>
  filter(DepthNames %in% c("50 m", "100 m")) |>
  mutate(DepthNames = factor(DepthNames, levels = c("100 m", "50 m")),
         lat = factor(lat, levels = c("45", "0"))) |>
  relocate(DepthNames, .after = lat) |>
  mutate(CladeHLI = case_when(DayofYear == "Winter Solstice" & lat == 45 ~ 0,
                              DayofYear == "Equinox" & DepthNames == "100 m" & lat == 45 ~ 0,
                              DayofYear == "Summer Solstice" & DepthNames == "100 m" & lat == 0  ~ 0,
                              TRUE ~ 1)) |>
  mutate(CladeLLII_LLIII = case_when(DayofYear == "Winter Solstice" & DepthNames == "100 m" & lat == 45 ~ 0,
                                     DayofYear == "Winter Solstice" & DepthNames == "50 m" & lat == 0 ~ 0,
                                     DayofYear == "Equinox" & DepthNames == "50 m" ~ 0,
                                     DayofYear == "Summer Solstice" & lat == 45  ~ 0,
                                     DayofYear == "Summer Solstice" & DepthNames == "50 m" & lat == 0  ~ 0,
                              TRUE ~ 1 ))  |>
  mutate(CladeLLIV = case_when(DayofYear == "Winter Solstice" & DepthNames == "100 m" & lat == 45 ~ 0,
                              TRUE ~ 1))

PhotoperiodDepthOMZ

PhotoperiodDepthFullO2 <- PhotoperiodDepth |>
  select(-c(ToD, DepthPARabs, DepthPARSine, DepthPARabsNA, Photicperiod:PhoticperiodSineSatPAR_h)) |>
  filter(DepthNames %in% c("50 m", "100 m")) |>
  mutate(DepthNames = factor(DepthNames, levels = c("100 m", "50 m")),
         lat = factor(lat, levels = c("45", "0"))) |>
  relocate(DepthNames, .after = lat) |>
  mutate(CladeHLI = case_when(DayofYear == "Winter Solstice" & DepthNames == "100 m" & lat == 45 ~ 0,
                              TRUE ~ 1)) |>
  mutate(CladeLLII_LLIII = case_when(DayofYear == "Winter Solstice" ~ 0,
                                     DayofYear == "Equinox" & DepthNames == "50 m" & lat == 45 ~ 0,
                                     DayofYear == "Equinox" & lat == 0 ~ 0,
                                     DayofYear == "Summer Solstice" & lat == 45  ~ 0,
                                     DayofYear == "Summer Solstice" & DepthNames == "50 m" & lat == 0  ~ 0,
                              TRUE ~ 1 ))  |>
  mutate(CladeLLIV = case_when(DayofYear == "Winter Solstice" & DepthNames == "100 m" & lat == 45 ~ 0,
                               DayofYear == "Winter Solstice" & DepthNames == "50 m" & lat == 0 ~ 0,
                               DayofYear == "Equinox" & DepthNames == "50 m" & lat == 45 ~ 0,
                               DayofYear == "Equinox" & lat == 0 ~ 0,
                               DayofYear == "Summer Solstice" & lat == 45  ~ 0,
                               DayofYear == "Summer Solstice" & DepthNames == "50 m" & lat == 0  ~ 0,
                              TRUE ~ 1))
  
PhotoperiodDepthFullO2

```


```{r read spectral depth backdrop}

library("png")
DepthBackdrop <- readPNG("DepthBackdrop.png")
# Get dimensions of the image
width <- dim(DepthBackdrop)[2]
height <- dim(DepthBackdrop)[1]

# Plot the image
plot(1:width, type = "n", xlim = c(0, width), ylim = c(0, height),
     xlab = "", ylab = "", axes =FALSE)
rasterImage(DepthBackdrop, 0, 0, width, height) 
points(PhotoperiodDepthFullO2$PhoticperiodPeakSatPAR_h, PhotoperiodDepthFullO2$DepthNames, col = "red", pch = 16) 
 


```
#fig.height = 10, fig.width = 8, warning = FALSE
```{r, Niches figures}
NichesFullO2North <- PhotoperiodDepthFullO2 %>%
  filter(lat == 45) %>% 
mutate(TextLabel = (case_when(CladeHLI == 1 & CladeLLII_LLIII == 0 & CladeLLIV == 0 ~ "Clade HLI",
                                CladeHLI == 1 & CladeLLII_LLIII == 1 & CladeLLIV == 0 ~ "Clades HLI, LLII/III",
                                CladeHLI == 1 & CladeLLII_LLIII == 1 & CladeLLIV == 1 ~ "Clades HLI, LLII/III, LLIV",
                                CladeLLII_LLIII == 1 & CladeHLI == 0 & CladeLLIV == 0 ~ "Clade LLII/III",
                                CladeLLII_LLIII == 1 & CladeHLI == 0 & CladeLLIV == 1 ~ "Clades LLII/III, LLIV",
                                CladeLLIV == 1 & CladeHLI == 0 & CladeLLII_LLIII == 0 ~ "Clade LLIV",
                                CladeLLIV == 1 & CladeHLI == 1 & CladeLLII_LLIII == 0 ~ "Clades HLI, LLIV",
                                CladeLLIV == 0 & CladeHLI == 0 & CladeLLII_LLIII == 0 ~ "")),
        TextLocation = 5) %>% 
mutate(DepthNames = factor(DepthNames, levels = c("50 m", "100 m")),
         lat = factor(lat, levels = c("45", "0"))) %>%
ggplot()+
  geom_point(aes(x = PhoticperiodPeakSatPAR_h, y = DepthNames),
            size = 0.5, alpha = 0, show.legend = TRUE)+
  labs(title = "Full Oxygen") +
  scale_x_continuous(breaks=seq(0, 25, by = 5)) +
    facet_grid(rows = vars(lat),
              cols = vars(DayofYear),
              labeller = labeller(lat = label_both, DayofYear = label_both)) +
   geom_text(aes(x = TextLocation, y = DepthNames, label = paste(TextLabel), show.legend = FALSE ),
   # parse = TRUE,
    hjust = 0,
    vjust = 1,
    size = 3
  )  +
  guides(color = "none") +
  theme_bw()+
 theme(strip.text = element_text(size = 10),
        axis.title = element_blank(),
        # strip.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 10),
        axis.text.x = element_blank(),
        axis.ticks.x.bottom = element_blank(),
        axis.ticks.y.left = element_blank(),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        plot.margin = unit(c(0,30,0,0), "pt"))

NichesFullO2North

NichesFullO2Equat <- PhotoperiodDepthFullO2 %>%
  filter(lat == 0) %>% 
mutate(TextLabel = (case_when(CladeHLI == 1 & CladeLLII_LLIII == 0 & CladeLLIV == 0 ~ "Clade HLI",
                                CladeHLI == 1 & CladeLLII_LLIII == 1 & CladeLLIV == 0 ~ "Clades HLI, LLII/III",
                                CladeHLI == 1 & CladeLLII_LLIII == 1 & CladeLLIV == 1 ~ "Clades HLI, LLII/III, LLIV",
                                CladeLLII_LLIII == 1 & CladeHLI == 0 & CladeLLIV == 0 ~ "Clade LLII/III",
                                CladeLLII_LLIII == 1 & CladeHLI == 0 & CladeLLIV == 1 ~ "Clades LLII/III, LLIV",
                                CladeLLIV == 1 & CladeHLI == 0 & CladeLLII_LLIII == 0 ~ "Clade LLIV",
                                CladeLLIV == 1 & CladeHLI == 1 & CladeLLII_LLIII == 0 ~ "Clades HLI, LLIV",
                                CladeLLIV == 0 & CladeHLI == 0 & CladeLLII_LLIII == 0 ~ "")),
        TextLocation = 5) %>% 
mutate(DepthNames = factor(DepthNames, levels = c("50 m", "100 m")),
         lat = factor(lat, levels = c("45", "0"))) %>%
ggplot()+
  geom_point(aes(x = PhoticperiodPeakSatPAR_h, y = DepthNames),
            size = 0.5, alpha = 0, show.legend = TRUE)+
  # labs(title = "Full Oxygen") +
  scale_x_continuous(breaks=seq(0, 25, by = 5)) +
    facet_grid(rows = vars(lat),
              cols = vars(DayofYear),
              labeller = labeller(lat = label_both)) +
   geom_text(aes(x = TextLocation, y = DepthNames, label = paste(TextLabel), show.legend = FALSE ),
   # parse = TRUE,
    hjust = 0,
    vjust = 1,
    size = 3
  )  +
  guides(color = "none") +
  theme_bw() +
 theme(strip.text.x = element_blank(),
       strip.text.y = element_text(size = 10),
        axis.title = element_blank(),
        # strip.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 10),
        # axis.text.y = element_blank(),
        # axis.text.y = element_text(size = 5),
         axis.text.x = element_blank(),
        axis.ticks.x.bottom = element_blank(),
        axis.ticks.y.left = element_blank(),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank())

NichesFullO2Equat





NichesOMZNorth <- PhotoperiodDepthOMZ %>%
  filter(lat == 45) %>% 
mutate(TextLabel = (case_when(CladeHLI == 1 & CladeLLII_LLIII == 0 & CladeLLIV == 0 ~ "Clade HLI",
                                CladeHLI == 1 & CladeLLII_LLIII == 1 & CladeLLIV == 0 ~ "Clades HLI, LLII/III",
                                CladeHLI == 1 & CladeLLII_LLIII == 1 & CladeLLIV == 1 ~ "Clades HLI, LLII/III, LLIV",
                                CladeLLII_LLIII == 1 & CladeHLI == 0 & CladeLLIV == 0 ~ "Clade LLII/III",
                                CladeLLII_LLIII == 1 & CladeHLI == 0 & CladeLLIV == 1 ~ "Clades LLII/III, LLIV",
                                CladeLLIV == 1 & CladeHLI == 0 & CladeLLII_LLIII == 0 ~ "Clade LLIV",
                                CladeLLIV == 1 & CladeHLI == 1 & CladeLLII_LLIII == 0 ~ "Clades HLI, LLIV",
                                CladeLLIV == 0 & CladeHLI == 0 & CladeLLII_LLIII == 0 ~ "")),
        TextLocation = 5) %>% 
mutate(DepthNames = factor(DepthNames, levels = c("50 m", "100 m")),
         lat = factor(lat, levels = c("45", "0"))) %>%
ggplot()+
  geom_point(aes(x = PhoticperiodPeakSatPAR_h, y = DepthNames),
            size = 0.5, alpha = 0, show.legend = TRUE)+
   labs(title = "OMZ") +
  scale_x_continuous(breaks=seq(0, 25, by = 5)) +
    facet_grid(rows = vars(lat),
              cols = vars(DayofYear),
              labeller = labeller(lat = label_both)) +
   geom_text(aes(x = TextLocation, y = DepthNames, label = paste(TextLabel), show.legend = FALSE ),
   # parse = TRUE,
    hjust = 0,
    vjust = 1,
    size = 3
  )  +
  guides(color = "none") +
  theme_bw() +
 theme(strip.text.x = element_text(size = 10),
       strip.text.y = element_text(size = 10),
        axis.title = element_blank(),
        # strip.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 10),
        # axis.text.y = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x.bottom = element_blank(),
        axis.ticks.y.left = element_blank(),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank())

NichesOMZNorth




NichesOMZEquat <- PhotoperiodDepthOMZ %>%
  filter(lat == 0) %>% 
mutate(TextLabel = (case_when(CladeHLI == 1 & CladeLLII_LLIII == 0 & CladeLLIV == 0 ~ "Clade HLI",
                                CladeHLI == 1 & CladeLLII_LLIII == 1 & CladeLLIV == 0 ~ "Clades HLI, LLII/III",
                                CladeHLI == 1 & CladeLLII_LLIII == 1 & CladeLLIV == 1 ~ "Clades HLI, LLII/III, LLIV",
                                CladeLLII_LLIII == 1 & CladeHLI == 0 & CladeLLIV == 0 ~ "Clade LLII/III",
                                CladeLLII_LLIII == 1 & CladeHLI == 0 & CladeLLIV == 1 ~ "Clades LLII/III, LLIV",
                                CladeLLIV == 1 & CladeHLI == 0 & CladeLLII_LLIII == 0 ~ "Clade LLIV",
                                CladeLLIV == 1 & CladeHLI == 1 & CladeLLII_LLIII == 0 ~ "Clades HLI, LLIV",
                                CladeLLIV == 0 & CladeHLI == 0 & CladeLLII_LLIII == 0 ~ "")),
        TextLocation = 5) %>% 
mutate(DepthNames = factor(DepthNames, levels = c("50 m", "100 m")),
         lat = factor(lat, levels = c("45", "0"))) %>%
ggplot()+
  geom_point(aes(x = PhoticperiodPeakSatPAR_h, y = DepthNames),
            size = 0.5, alpha = 0, show.legend = TRUE)+
  # labs(title = "Full Oxygen") +
  scale_x_continuous(breaks=seq(0, 25, by = 5)) +
    facet_grid(rows = vars(lat),
              cols = vars(DayofYear),
              labeller = labeller(lat = label_both)) +
   geom_text(aes(x = TextLocation, y = DepthNames, label = paste(TextLabel), show.legend = FALSE ),
   # parse = TRUE,
    hjust = 0,
    vjust = 1,
    size = 3
  )  +
  guides(color = "none") +
  theme_bw() +
 theme(strip.text.x = element_blank(),
       strip.text.y = element_text(size = 10),
        axis.title = element_blank(),
        # strip.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 10),
        # axis.text.y = element_blank(),
         axis.text.x = element_blank(),
        axis.ticks.x.bottom = element_blank(),
        axis.ticks.y.left = element_blank(),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank())

NichesOMZEquat

```



# Create map
https://www.geeksforgeeks.org/how-to-make-world-map-with-ggplot2-in-r/

```{r world map}
world_coordinates <- map_data("world") 
# world_coordinates$facetsFuture <- 'Future~scenario'

data_textA <- data.frame(label = c('A'))
data_textB <- data.frame(label = c('B'))
# data_textC <- data.frame(label = c('C'))
```


```{r create maps, fig.height = 10, fig.width = 6, warning = FALSE}

d=data.frame(x1=c(-Inf), x2=c(Inf), y1=c(35), y2=c(55))
d2=data.frame(x1=c(-Inf), x2=c(Inf), y1=c(-35), y2=c(-55))
d3=data.frame(x1=c(-Inf), x2=c(Inf), y1=c(-Inf), y2=c(Inf))
d4=data.frame(x1=c(-Inf), x2=c(Inf), y1=c(-15), y2=c(15))
d5=data.frame(x1=c(-Inf), x2=c(Inf), y1=c(-40), y2=c(40))
# 
# data_textTropicFull <- data.frame(label = c('All~year'))
# data_textTropicFull2 <- data.frame(label = c('12~h'))
# data_textTropicFull3 <- data.frame(label = c('11/7~h'))
# 
# TropicFull<-ggplot() + 
#   geom_rect(data=d3, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "lightskyblue1", color="lightskyblue3", alpha=0.5) +
#   geom_rect(data=d4, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "khaki1", color="khaki2", alpha=0.8) +
#   geom_hline(yintercept = 40, fill = "transparent", color="olivedrab3", linetype = "dashed", alpha=1, size = 1) +
#   geom_hline(yintercept = -40, fill = "transparent", color="olivedrab3", linetype = "dashed", alpha=1, size = 1) +
#   geom_map(data = world_coordinates, map = world_coordinates, aes(long, lat, map_id = region), color = "white", fill = "gray50", size = 0.2) +
#   geom_text(data=data_textA, aes(x=180, y=120, label=label), size=7, parse=TRUE) +
#   geom_text(data=data_textTropicFull, aes(x=0, y=110, label=label), size=5, parse=TRUE) +
#   geom_text(data=data_textTropicFull2, aes(x=-180, y=0, label=label), size=3.5, parse=TRUE) +
#   geom_text(data=data_textTropicFull3, aes(x=180, y=0, label=label), size=3.5, parse=TRUE) +
#   scale_y_continuous(breaks=seq(-90, 90, by = 45)) +
#   coord_cartesian(ylim = c(-90, 120)) +
#   labs(y = "Latitude", x = "Longitude") +
#   ggh4x::facet_nested(rows = vars(facetsPresent), labeller = label_parsed, switch = "y") +
#   theme_bw() +
#   theme(panel.grid.minor = element_blank(),
#         panel.grid.major = element_blank(),
#         strip.placement = "outside",
#         strip.switch.pad.grid = unit(1, "cm"),
#         axis.text = element_text(size=14),
#         axis.title = element_text(size=14),
#         strip.background = element_rect(fill="white"),
#         strip.text = element_text(size=18),
#         axis.title.y = element_text(vjust = -15),
#         #axis.title.x = element_text(margin=margin(t=10)),
#         axis.title.x = element_blank(),
#         axis.text.x = element_blank(),
#         axis.ticks.x = element_blank(),
#         legend.background = element_rect(fill="transparent"),
#         legend.position = c(0.12,0.76),
#         legend.key.height= unit(0.005, 'cm'),
#         legend.spacing.x = unit(0.01, 'cm'),
#         legend.text = element_text(size=14))
# TropicFull

# data_textWinterFull <- data.frame(label = c('Winter~or~summer~solstice'))
# data_textWinterFull2 <- data.frame(label = c('9~h'))
# data_textWinterFull3 <- data.frame(label = c('16~h'))
# data_textWinterFull4 <- data.frame(label = c('8/4~h'))
# data_textWinterFull5 <- data.frame(label = c('15/10~h'))

FullO2map<-ggplot() + 
  geom_rect(data=d3, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "lightskyblue1", color="lightskyblue3", alpha=0.5) +
  geom_rect(data=d, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "khaki1", color="khaki2", alpha=0.8) +
  geom_rect(data=d2, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "khaki1", color="khaki2", alpha=0.8) +
    geom_rect(data=d4, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "khaki1", color="khaki2", alpha=0.8) +
  geom_hline(yintercept = 40, fill = "transparent", color="olivedrab3", linetype = "dashed", alpha=1, size = 1) +
  geom_hline(yintercept = -40, fill = "transparent", color="olivedrab3", linetype = "dashed", alpha=1, size = 1) +
  geom_map(data = world_coordinates, map = world_coordinates, aes(long, lat, map_id = region), color = "white", fill = "gray50", size = 0.2) +
    geom_text(data=data_textA, aes(x=180, y=120, label=label), size=7, parse=TRUE) +
    # geom_text(data=data_textWinterFull, aes(x=0, y=110, label=label), size=5, parse=TRUE) +
    # geom_text(data=data_textWinterFull2, aes(x=-180, y=50, label=label), size=3.5, parse=TRUE) +
    # geom_text(data=data_textWinterFull3, aes(x=-180, y=-50, label=label), size=3.5, parse=TRUE) +
    # geom_text(data=data_textWinterFull4, aes(x=180, y=50, label=label), size=3.5, parse=TRUE) +
    # geom_text(data=data_textWinterFull5, aes(x=180, y=-50, label=label), size=3.5, parse=TRUE) +
    # geom_text(data=data_textTropicFull2, aes(x=-180, y=0, label=label), size=3.5, parse=TRUE) +
    # geom_text(data=data_textTropicFull3, aes(x=180, y=0, label=label), size=3.5, parse=TRUE) +
  scale_y_continuous(breaks=seq(-90, 90, by = 45)) +
  coord_cartesian(ylim = c(-90, 120)) +
  labs(y = "Latitude", x = "Longitude") +
  # ggh4x::facet_nested(rows = vars(facetsFuture), labeller = label_parsed, switch = "y") +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        strip.placement = "outside",
        strip.switch.pad.grid = unit(1, "cm"),
        axis.text = element_text(size=14),
        axis.title = element_text(size=14),
        strip.background = element_rect(fill="white"),
        strip.text = element_text(size=18),
        axis.title.y = element_text(vjust = 1),
        #axis.title.x = element_text(margin=margin(t=10)),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.background = element_rect(fill="transparent"),
        legend.position = c(0.12,0.76),
        legend.key.height= unit(0.005, 'cm'),
        legend.spacing.x = unit(0.01, 'cm'),
        legend.text = element_text(size=14))
FullO2map


# data_textSpringFull <- data.frame(label = c('Vernal~equinox'))
# data_textSpringFull2 <- data.frame(label = c('12~h'))
# data_textSpringFull3 <- data.frame(label = c('12~h'))
# 
# data_textSpringFull4 <- data.frame(label = c('11/6~h'))
# data_textSpringFull5 <- data.frame(label = c('11/6~h'))

OMZmap<-ggplot() + 
  geom_rect(data=d3, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "lightskyblue1", color="lightskyblue3", alpha=0.5) +
  geom_rect(data=d, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "khaki1", color="khaki2", alpha=0.8) +
  geom_rect(data=d2, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "khaki1", color="khaki2", alpha=0.8) +
  geom_rect(data=d4, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "khaki1", color="khaki2", alpha=0.8) +
  geom_hline(yintercept = 40, fill = "transparent", color="olivedrab3", linetype = "dashed", alpha=1, size = 1) +
  geom_hline(yintercept = -40, fill = "transparent", color="olivedrab3", linetype = "dashed", alpha=1, size = 1) +
  geom_map(data = world_coordinates, map = world_coordinates, aes(long, lat, map_id = region), color = "white", fill = "gray50", size = 0.2) +
     geom_text(data=data_textB, aes(x=180, y=120, label=label), size=7, parse=TRUE) +
    # geom_text(data=data_textSpringFull, aes(x=0, y=110, label=label), size=5, parse=TRUE) +
    # geom_text(data=data_textSpringFull2, aes(x=-180, y=50, label=label), size=3.5, parse=TRUE) +
    # geom_text(data=data_textSpringFull3, aes(x=-180, y=-50, label=label), size=3.5, parse=TRUE) +
    # geom_text(data=data_textSpringFull4, aes(x=180, y=50, label=label), size=3.5, parse=TRUE) +
    # geom_text(data=data_textSpringFull5, aes(x=180, y=-50, label=label), size=3.5, parse=TRUE) +
    # geom_text(data=data_textTropicFull2, aes(x=-180, y=0, label=label), size=3.5, parse=TRUE) +
    # geom_text(data=data_textTropicFull3, aes(x=180, y=0, label=label), size=3.5, parse=TRUE) +
    # 
  scale_y_continuous(breaks=seq(-90, 90, by = 45)) +
  coord_cartesian(ylim = c(-90, 120)) +
  labs(y = "Latitude", x = "Longitude") +
  # ggh4x::facet_nested(rows = vars(facetsFuture), labeller = label_parsed, switch = "y") +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        strip.placement = "outside",
        strip.switch.pad.grid = unit(1, "cm"),
        axis.text = element_text(size=14),
        axis.title = element_text(size=14),
        strip.background = element_rect(fill="white"),
        strip.text = element_text(size=18),
        axis.title.y = element_text(vjust = 1),
        #axis.title.x = element_text(margin=margin(t=10)),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.background = element_rect(fill="transparent"),
        legend.position = c(0.12,0.76),
        legend.key.height= unit(0.005, 'cm'),
        legend.spacing.x = unit(0.01, 'cm'),
        legend.text = element_text(size=14))
OMZmap

# data_textSummerFull <- data.frame(label = c('Summer~or~winter~solstice'))
# data_textSummerFull2 <- data.frame(label = c('16~h'))
# data_textSummerFull3 <- data.frame(label = c('9~h'))
# data_textSummerFull4 <- data.frame(label = c('15/10~h'))
# data_textSummerFull5 <- data.frame(label = c('8/4~h'))
# SummerFull<-ggplot() + 
#   geom_rect(data=d3, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "lightskyblue1", color="lightskyblue3", alpha=0.5) +
#   geom_rect(data=d, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "khaki1", color="khaki2", alpha=0.8) +
#   geom_rect(data=d2, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "khaki1", color="khaki2", alpha=0.8) +
#     geom_rect(data=d4, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "khaki1", color="khaki2", alpha=0.8) +
#   geom_hline(yintercept = 40, fill = "transparent", color="olivedrab3", linetype = "dashed", alpha=1, size = 1) +
#   geom_hline(yintercept = -40, fill = "transparent", color="olivedrab3", linetype = "dashed", alpha=1, size = 1) +
#   geom_map(data = world_coordinates, map = world_coordinates, aes(long, lat, map_id = region), color = "white", fill = "gray50", size = 0.2) +
#     geom_text(data=data_textD, aes(x=180, y=120, label=label), size=7, parse=TRUE) +
#     geom_text(data=data_textSummerFull, aes(x=0, y=110, label=label), size=5, parse=TRUE) +
#     geom_text(data=data_textSummerFull2, aes(x=-180, y=50, label=label), size=3.5, parse=TRUE) +
#     geom_text(data=data_textSummerFull3, aes(x=-180, y=-50, label=label), size=3.5, parse=TRUE) +
#     geom_text(data=data_textSummerFull4, aes(x=180, y=50, label=label), size=3.5, parse=TRUE) +
#     geom_text(data=data_textSummerFull5, aes(x=180, y=-50, label=label), size=3.5, parse=TRUE) +
#       geom_text(data=data_textTropicFull2, aes(x=-180, y=0, label=label), size=3.5, parse=TRUE) +
#       geom_text(data=data_textTropicFull3, aes(x=180, y=0, label=label), size=3.5, parse=TRUE) +
#   scale_y_continuous(breaks=seq(-90, 90, by = 45)) +
#   coord_cartesian(ylim = c(-90, 120)) +
#   labs(y = "Latitude", x = "Longitude") +
#   ggh4x::facet_nested(rows = vars(facetsFuture), labeller = label_parsed, switch = "y") +
#   theme_bw() +
#   theme(panel.grid.minor = element_blank(),
#         panel.grid.major = element_blank(),
#         strip.placement = "outside",
#         strip.switch.pad.grid = unit(1, "cm"),
#         axis.text = element_text(size=14),
#         axis.title = element_text(size=14),
#         strip.background = element_rect(fill="white"),
#         strip.text = element_text(size=18),
#         axis.title.y = element_text(vjust = -15),
#         #axis.title.x = element_text(margin=margin(t=10)),
#         axis.title.x = element_blank(),
#         axis.text.x = element_blank(),
#         axis.ticks.x = element_blank(),
#         legend.background = element_rect(fill="transparent"),
#         legend.position = c(0.12,0.76),
#         legend.key.height= unit(0.005, 'cm'),
#         legend.spacing.x = unit(0.01, 'cm'),
#         legend.text = element_text(size=14))
# SummerFull



```


```{r, warning = FALSE, fig.height = 15, fig.width = 20}

FullO2<- (FullO2map + (plot_spacer()/NichesFullO2North/NichesFullO2Equat/plot_spacer())) +
  plot_layout(widths = c(3,2), heights = c(4,0.5))
FullO2  

OMZ<- (OMZmap + (plot_spacer()/NichesOMZNorth/NichesOMZEquat/plot_spacer())) +
  plot_layout(widths = c(3,2), heights = c(4,0.5))
OMZ 

NichesMap <- (FullO2map + (plot_spacer()/NichesFullO2North/NichesFullO2Equat/plot_spacer())) / (OMZmap + (plot_spacer()/NichesOMZNorth/NichesOMZEquat/plot_spacer()))

NichesMap

```

```{r save plot}
#ggsave(file = file.path(FigPath, paste("NichesMap",".png",sep = "")), height=16, width= 24,  dpi = 300, limitsize = TRUE)
```


-------------------------------------------------------------------------------------------------------------------
---------------------------------------------- # SySl changes-----------------------------------------------------------
----------------------------------------------------------------------------------------------------------------



fig.height = 10, fig.width = 6, warning = FALSE
```{r create maps, fig.height = 8, fig.width = 10, warning = FALSE}

d=data.frame(x1=c(-Inf), x2=c(Inf), y1=c(35), y2=c(55))
d2=data.frame(x1=c(-Inf), x2=c(Inf), y1=c(-35), y2=c(-55))
d3=data.frame(x1=c(-Inf), x2=c(Inf), y1=c(-Inf), y2=c(Inf))
d4=data.frame(x1=c(-Inf), x2=c(Inf), y1=c(-15), y2=c(15))
d5=data.frame(x1=c(-Inf), x2=c(Inf), y1=c(-40), y2=c(40))


map<-ggplot() + 
  geom_rect(data=d3, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "lightskyblue1", color="lightskyblue3", alpha=0.5) +
  geom_rect(data=d, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "khaki1", color="khaki2", alpha=0.8) +
  geom_rect(data=d2, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "khaki1", color="khaki2", alpha=0.8) +
    geom_rect(data=d4, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "khaki1", color="khaki2", alpha=0.8) +
  geom_hline(yintercept = 40, fill = "transparent", color="chartreuse4", linetype = "dashed", alpha=1, size = 1) +
  geom_hline(yintercept = -40, fill = "transparent", color="chartreuse4", linetype = "dashed", alpha=1, size = 1) +
  geom_map(data = world_coordinates, map = world_coordinates, aes(long, lat, map_id = region), color = "gray50", fill = "gray50", size = 0.2) +
   # geom_text(data=data_textA, aes(x=180, y=120, label=label), size=7, parse=TRUE) +
  scale_y_continuous(breaks=seq(-90, 90, by = 45)) +
  coord_cartesian(ylim = c(-90, 120)) +
  coord_fixed(ratio = 2, xlim = NULL, ylim = NULL, expand = TRUE, clip = "on") +
  labs(y = "Latitude", x = "Longitude") +
  # ggh4x::facet_nested(rows = vars(facetsFuture), labeller = label_parsed, switch = "y") +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        axis.text = element_text(size=20),
        axis.title = element_text(size=22),
        strip.background = element_rect(fill="white"),
        strip.text = element_text(size=20),
        #axis.title.x = element_text(margin=margin(t=10)),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.background = element_rect(fill="transparent"),
        legend.position = c(0.12,0.76),
        legend.key.height= unit(0.005, 'cm'),
        legend.spacing.x = unit(0.01, 'cm'),
        legend.text = element_text(size=14)) 
map

```

```{r create maps, fig.height = 8, fig.width = 14, warning = FALSE}
world_coordinates2 <- map_data("world") %>% 
  filter(! long > 180) 

mapCircle<-ggplot() + 
  geom_rect(data=d3, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "lightskyblue1", color="lightskyblue3", alpha=0.5) +
  geom_rect(data=d, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "khaki1", color="khaki2", alpha=0.8) +
  geom_rect(data=d2, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "khaki1", color="khaki2", alpha=0.8) +
    geom_rect(data=d4, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "khaki1", color="khaki2", alpha=0.8) +
  geom_hline(yintercept = 40, fill = "transparent", color="chartreuse4", linetype = "dashed", alpha=1, size = 1) +
  geom_hline(yintercept = -40, fill = "transparent", color="chartreuse4", linetype = "dashed", alpha=1, size = 1) +
  geom_map(data = world_coordinates2, map = world_coordinates2, aes(long, lat, map_id = region), color = "gray50", fill = "gray50", size = 0.2) +
   # geom_text(data=data_textA, aes(x=180, y=120, label=label), size=7, parse=TRUE) +
  scale_y_continuous(breaks=seq(-90, 90, by = 45)) +
  coord_cartesian(ylim = c(-90, 90)) +
  #coord_fixed(ratio = 2, xlim = NULL, ylim = NULL, expand = TRUE, clip = "on") +
  labs(y = "Latitude", x = "Longitude") +
  # ggh4x::facet_nested(rows = vars(facetsFuture), labeller = label_parsed, switch = "y") +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        axis.text = element_text(size=20),
        axis.title = element_text(size=22),
        strip.background = element_rect(fill="white"),
        strip.text = element_text(size=20),
        #axis.title.x = element_text(margin=margin(t=10)),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.background = element_rect(fill="transparent"),
        legend.position = c(0.12,0.76),
        legend.key.height= unit(0.005, 'cm'),
        legend.spacing.x = unit(0.01, 'cm'),
        legend.text = element_text(size=14)) +
    coord_map("moll") 
mapCircle

```


#fig.height = 10, fig.width = 8, warning = FALSE
   # parse = TRUE,
    hjust = 0,
    vjust = 1,
```{r, Niches figures, fig.height = 4, fig.width = 8, warning = FALSE}

d=data.frame(x=c(-Inf,700,700), y=c(-Inf,-Inf,3), t=c('a', 'a', 'a'), r=c(1,2,3))

PhotoperiodDepthFullO2<-PhotoperiodDepthFullO2
PhotoperiodDepthFullO2$nm <- c(400, 400, 400, 400, 400, 400, 700, 700, 700, 700, 700, 700)

PhotoperiodDepthOMZ<-PhotoperiodDepthOMZ
PhotoperiodDepthOMZ$nm <- c(400, 400, 400, 400, 400, 400, 700, 700, 700, 700, 700, 700)



NichesFullO2North <- PhotoperiodDepthFullO2 %>%
  filter(lat == 45) %>% 
mutate(TextLabel = (case_when(CladeHLI == 1 & CladeLLII_LLIII == 0 & CladeLLIV == 0 ~ "HLI",
                                CladeHLI == 1 & CladeLLII_LLIII == 1 & CladeLLIV == 0 ~ "HLI, LLII/III",
                                CladeHLI == 1 & CladeLLII_LLIII == 1 & CladeLLIV == 1 ~ "HLI, LLII/III, LLIV",
                                CladeLLII_LLIII == 1 & CladeHLI == 0 & CladeLLIV == 0 ~ "LLII/III",
                                CladeLLII_LLIII == 1 & CladeHLI == 0 & CladeLLIV == 1 ~ "LLII/III, LLIV",
                                CladeLLIV == 1 & CladeHLI == 0 & CladeLLII_LLIII == 0 ~ "LLIV",
                                CladeLLIV == 1 & CladeHLI == 1 & CladeLLII_LLIII == 0 ~ "HLI, LLIV",
                                CladeLLIV == 0 & CladeHLI == 0 & CladeLLII_LLIII == 0 ~ "")),
        TextLocation = 400) %>% 
ggplot()+
  geom_point(aes(x = nm, y = DepthNames), size = 0.5, alpha = 0, show.legend = TRUE)+
  stat_wl_strip(aes(x = nm), ymin = -Inf, ymax = Inf, alpha = 0.3, PhotoperiodDepthFullO2) +
  scale_fill_identity() +
  # scale_x_continuous(breaks=seq(0, 25, by = 5)) +
  # coord_cartesian(xlim = c(0, 20)) +
  coord_fixed(ratio = 55, xlim = NULL, ylim = NULL, expand = TRUE, clip = "on") +
  #geom_ellipse(aes(x0 = 555, y0 = 1.43, a = 10, b = 2, angle = pi / 1), fill = "transparent", colour = "transparent") +
  geom_polygon(data=d, mapping=aes(x=x, y=y, group=t), fill = "white", show.legend = F) +
  geom_text(aes(x = TextLocation, y = DepthNames, label = paste(TextLabel), show.legend = FALSE), hjust = 0, size = 6.5)  +
  ggh4x::facet_nested(cols = vars(DayofYear), labeller = labeller(lat = label_both)) +
  guides(color = "none") +
  labs(title = "Full Oxygen") +
  theme_bw() +
  theme(plot.title = element_text(size = 22),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        axis.text = element_text(size=20),
        #axis.title = element_text(size=14),
        strip.background = element_rect(fill="white"),
        strip.text = element_text(size=18),
        #axis.title.y = element_text(vjust = 1),
        #axis.title.x = element_text(margin=margin(t=10)),
        axis.title = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.background = element_rect(fill="transparent"),
        legend.position = c(0.12,0.76),
        legend.key.height= unit(0.005, 'cm'),
        legend.spacing.x = unit(0.01, 'cm'),
        legend.text = element_text(size=14)) 
NichesFullO2North


NichesFullO2Equat <- PhotoperiodDepthFullO2 %>%
  filter(lat == 0) %>% 
mutate(TextLabel = (case_when(CladeHLI == 1 & CladeLLII_LLIII == 0 & CladeLLIV == 0 ~ "HLI",
                                CladeHLI == 1 & CladeLLII_LLIII == 1 & CladeLLIV == 0 ~ "HLI, LLII/III",
                                CladeHLI == 1 & CladeLLII_LLIII == 1 & CladeLLIV == 1 ~ "HLI, LLII/III, LLIV",
                                CladeLLII_LLIII == 1 & CladeHLI == 0 & CladeLLIV == 0 ~ "LLII/III",
                                CladeLLII_LLIII == 1 & CladeHLI == 0 & CladeLLIV == 1 ~ "LLII/III, LLIV",
                                CladeLLIV == 1 & CladeHLI == 0 & CladeLLII_LLIII == 0 ~ "LLIV",
                                CladeLLIV == 1 & CladeHLI == 1 & CladeLLII_LLIII == 0 ~ "HLI, LLIV",
                                CladeLLIV == 0 & CladeHLI == 0 & CladeLLII_LLIII == 0 ~ "")),
        TextLocation = 400) %>% 
ggplot()+
  geom_point(aes(x = nm, y = DepthNames), size = 0.5, alpha = 0, show.legend = TRUE)+
  stat_wl_strip(aes(x = nm), ymin = -Inf, ymax = Inf, alpha = 0.3, PhotoperiodDepthFullO2) +
  scale_fill_identity() +
  # scale_x_continuous(breaks=seq(0, 25, by = 5)) +
  # coord_cartesian(xlim = c(0, 20)) +
  coord_fixed(ratio = 55, xlim = NULL, ylim = NULL, expand = TRUE, clip = "on") +
  #geom_ellipse(aes(x0 = 555, y0 = 1.43, a = 10, b = 2, angle = pi / 1), fill = "transparent", colour = "transparent") +
  geom_polygon(data=d, mapping=aes(x=x, y=y, group=t), fill = "white", show.legend = F) +
  geom_text(aes(x = TextLocation, y = DepthNames, label = paste(TextLabel), show.legend = FALSE), hjust = 0, size = 6.5)  +
  ggh4x::facet_nested(cols = vars(DayofYear), labeller = labeller(lat = label_both)) +
  guides(color = "none") +
  theme_bw() +
  theme(plot.title = element_text(vjust = 10),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        axis.text = element_text(size=20),
        #axis.title = element_text(size=14),
        strip.background = element_rect(fill="white"),
        strip.text = element_text(size=18),
        #axis.title.y = element_text(vjust = 1),
        #axis.title.x = element_text(margin=margin(t=10)),
        axis.title = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.background = element_rect(fill="transparent"),
        legend.position = c(0.12,0.76),
        legend.key.height= unit(0.005, 'cm'),
        legend.spacing.x = unit(0.01, 'cm'),
        legend.text = element_text(size=14)) 

NichesFullO2Equat





NichesOMZNorth <- PhotoperiodDepthOMZ %>%
  filter(lat == 45) %>% 
mutate(TextLabel = (case_when(CladeHLI == 1 & CladeLLII_LLIII == 0 & CladeLLIV == 0 ~ "HLI",
                                CladeHLI == 1 & CladeLLII_LLIII == 1 & CladeLLIV == 0 ~ "HLI, LLII/III",
                                CladeHLI == 1 & CladeLLII_LLIII == 1 & CladeLLIV == 1 ~ "HLI, LLII/III, LLIV",
                                CladeLLII_LLIII == 1 & CladeHLI == 0 & CladeLLIV == 0 ~ "LLII/III",
                                CladeLLII_LLIII == 1 & CladeHLI == 0 & CladeLLIV == 1 ~ "LLII/III, LLIV",
                                CladeLLIV == 1 & CladeHLI == 0 & CladeLLII_LLIII == 0 ~ "LLIV",
                                CladeLLIV == 1 & CladeHLI == 1 & CladeLLII_LLIII == 0 ~ "HLI, LLIV",
                                CladeLLIV == 0 & CladeHLI == 0 & CladeLLII_LLIII == 0 ~ "")),
        TextLocation = 400) %>% 
ggplot()+
  geom_point(aes(x = nm, y = DepthNames), size = 0.5, alpha = 0, show.legend = TRUE)+
  stat_wl_strip(aes(x = nm), ymin = -Inf, ymax = Inf, alpha = 0.3, PhotoperiodDepthOMZ) +
  scale_fill_identity() +
  # scale_x_continuous(breaks=seq(0, 25, by = 5)) +
  # coord_cartesian(xlim = c(0, 20)) +
  coord_fixed(ratio = 55, xlim = NULL, ylim = NULL, expand = TRUE, clip = "on") +
  #geom_ellipse(aes(x0 = 555, y0 = 1.43, a = 10, b = 2, angle = pi / 1), fill = "transparent", colour = "transparent") +
  geom_polygon(data=d, mapping=aes(x=x, y=y, group=t), fill = "white", show.legend = F) +
  geom_text(aes(x = TextLocation, y = DepthNames, label = paste(TextLabel), show.legend = FALSE), hjust = 0, size = 6.5)  +
  ggh4x::facet_nested(cols = vars(DayofYear), labeller = labeller(lat = label_both)) +
  guides(color = "none") +
  labs(title = "Oxygen Minimum Zone") +
  theme_bw() +
  theme(plot.title = element_text(size = 22),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        axis.text = element_text(size=20),
        #axis.title = element_text(size=14),
        strip.background = element_rect(fill="white"),
        strip.text = element_text(size=18),
        #axis.title.y = element_text(vjust = 1),
        #axis.title.x = element_text(margin=margin(t=10)),
        axis.title = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.background = element_rect(fill="transparent"),
        legend.position = c(0.12,0.76),
        legend.key.height= unit(0.005, 'cm'),
        legend.spacing.x = unit(0.01, 'cm'),
        legend.text = element_text(size=14)) 

NichesOMZNorth



NichesOMZEquat <- PhotoperiodDepthOMZ %>%
  filter(lat == 0) %>% 
mutate(TextLabel = (case_when(CladeHLI == 1 & CladeLLII_LLIII == 0 & CladeLLIV == 0 ~ "HLI",
                                CladeHLI == 1 & CladeLLII_LLIII == 1 & CladeLLIV == 0 ~ "HLI, LLII/III",
                                CladeHLI == 1 & CladeLLII_LLIII == 1 & CladeLLIV == 1 ~ "HLI, LLII/III, LLIV",
                                CladeLLII_LLIII == 1 & CladeHLI == 0 & CladeLLIV == 0 ~ "LLII/III",
                                CladeLLII_LLIII == 1 & CladeHLI == 0 & CladeLLIV == 1 ~ "LLII/III, LLIV",
                                CladeLLIV == 1 & CladeHLI == 0 & CladeLLII_LLIII == 0 ~ "LLIV",
                                CladeLLIV == 1 & CladeHLI == 1 & CladeLLII_LLIII == 0 ~ "HLI, LLIV",
                                CladeLLIV == 0 & CladeHLI == 0 & CladeLLII_LLIII == 0 ~ "")),
        TextLocation = 400) %>% 

ggplot()+
  geom_point(aes(x = nm, y = DepthNames), size = 0.5, alpha = 0, show.legend = TRUE)+
  stat_wl_strip(aes(x = nm), ymin = -Inf, ymax = Inf, alpha = 0.3, PhotoperiodDepthOMZ) +
  scale_fill_identity() +
  # scale_x_continuous(breaks=seq(0, 25, by = 5)) +
  # coord_cartesian(xlim = c(0, 20)) +
  coord_fixed(ratio = 55, xlim = NULL, ylim = NULL, expand = TRUE, clip = "on") +
  #geom_ellipse(aes(x0 = 555, y0 = 1.43, a = 10, b = 2, angle = pi / 1), fill = "transparent", colour = "transparent") +
  geom_polygon(data=d, mapping=aes(x=x, y=y, group=t), fill = "white", show.legend = F) +
  geom_text(aes(x = TextLocation, y = DepthNames, label = paste(TextLabel), show.legend = FALSE), hjust = 0, size = 6.5)  +
  ggh4x::facet_nested(cols = vars(DayofYear), labeller = labeller(lat = label_both)) +
  guides(color = "none") +
  theme_bw() +
  theme(plot.title = element_text(vjust = 10),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        axis.text = element_text(size=20),
        #axis.title = element_text(size=14),
        strip.background = element_rect(fill="white"),
        strip.text = element_text(size=18),
        #axis.title.y = element_text(vjust = 1),
        #axis.title.x = element_text(margin=margin(t=10)),
        axis.title = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.background = element_rect(fill="transparent"),
        legend.position = c(0.12,0.76),
        legend.key.height= unit(0.005, 'cm'),
        legend.spacing.x = unit(0.01, 'cm'),
        legend.text = element_text(size=14)) 


NichesOMZEquat

```


```{r}
# P1<-(NichesFullO2North/NichesFullO2Equat)
# P1
# 
# P2<- (NichesOMZNorth/NichesOMZEquat)
# P2 
# 
# ggarrange(P1, map, P2, ncol = 3, nrow = 1)

```

#Cool web about merging plots
http://www.sthda.com/english/articles/24-ggpubr-publication-ready-plots/81-ggplot2-easy-way-to-mix-multiple-graphs-on-the-same-page/

```{r, fig.height = 4, fig.width = 8, warning = FALSE}

ggdraw() +
  draw_plot(NichesFullO2North, x = 0, y = 0.65, width = .3, height = .3) +
  draw_plot(NichesFullO2Equat, x = 0, y = 0.455, width = .3, height = .3) +
  draw_plot(map, x = .1, y = .2, width = 0.8, height = 0.8) +
  draw_plot(NichesOMZNorth, x = 0.7, y = 0.65, width = .3, height = 0.3) +
  draw_plot(NichesOMZEquat, x = 0.7, y = 0.455, width = .3, height = 0.3) 

ggsave(file = file.path(FigPath, paste("NichesMap",".png",sep = "")), height=12, width= 28,  dpi = 300, limitsize = TRUE)



ggdraw() +
  draw_plot(NichesFullO2North, x = 0, y = 0.68, width = .26, height = .26) +
  draw_plot(NichesFullO2Equat, x = 0, y = 0.51, width = .26, height = .26) +
  draw_plot(mapCircle, x = .26, y = .29, width = 0.46, height = 0.7) +
  draw_plot(NichesOMZNorth, x = 0.72, y = 0.68, width = .26, height = 0.26) +
  draw_plot(NichesOMZEquat, x = 0.72, y = 0.51, width = .26, height = 0.26) 

ggsave(file = file.path(FigPath, paste("NichesMap_2",".png",sep = "")), height=12, width= 30,  dpi = 300, limitsize = TRUE)
```


```{r save plot}
#ggsave(file = file.path(FigPath, paste("NichesMap",".png",sep = "")), height=12, width= 28,  dpi = 300, limitsize = TRUE)

#ggsave(file = file.path(FigPath, paste("NichesMap_3",".png",sep = "")), height=12, width= 30,  dpi = 300, limitsize = TRUE)
```


```{r, fig.height = 8, fig.width = 16, warning = FALSE}

P1<-ggdraw() +
  draw_plot(NichesFullO2North, x = 0.001, y = 0.695, width = .36, height = .22) +
  draw_plot(NichesFullO2Equat, x = 0.001, y = 0.485, width = .36, height = .22) +
  draw_plot(map, x = .179, y = .2, width = 0.8, height = 0.8) 
P1

P2<-ggdraw() +
  draw_plot(NichesOMZNorth, x = 0.001, y = 0.695, width = .36, height = .22) +
  draw_plot(NichesOMZEquat, x = 0.001, y = 0.485, width = .36, height = .22) +
  draw_plot(map, x = .179, y = .2, width = 0.8, height = 0.8) 
P2


ggarrange(P1, P2, ncol = 1, nrow = 2)

ggsave(file = file.path(FigPath, paste("NichesMap_3",".png",sep = "")), height=18, width= 20,  dpi = 300, limitsize = TRUE)
```

```{r, fig.height = 8, fig.width = 16, warning = FALSE}

P1<-ggdraw() +
  draw_plot(NichesFullO2North, x = 0.001, y = 0.750, width = .350, height = .22) +
  draw_plot(NichesFullO2Equat, x = 0.001, y = 0.510, width = .350, height = .22) +
  draw_plot(mapCircle, x = .350, y = .28, width = 0.7, height = 0.7) 
P1

P2<-ggdraw() +
  draw_plot(NichesOMZNorth, x = 0.001, y = 0.750, width = .350, height = .22) +
  draw_plot(NichesOMZEquat, x = 0.001, y = 0.510, width = .350, height = .22) +
  draw_plot(mapCircle, x = .350, y = .28, width = 0.7, height = 0.7) 
P2


ggarrange(P1, P2, ncol = 1, nrow = 2)

ggsave(file = file.path(FigPath, paste("NichesMap_4",".png",sep = "")), height=18, width= 21,  dpi = 300, limitsize = TRUE)
```




-----------------------------------------------------------------------------------------------------------------
------------------------------------------- SySl End ----------------------------------------------------------
---------------------------------------------------------------------------------------------------------------





https://sape.inf.usi.ch/quick-reference/ggplot2/geom_polygon


```{r, warning = FALSE, fig.height = 12, fig.width = 6}
# OMZRainbow<- (TropicOMZRainbow/SpringOMZRainbow/SummerOMZRainbow/WinterOMZRainbow)
# OMZRainbow                         
```


```{r, warning = FALSE, fig.height = 16, fig.width = 22}
# MapCombo<-((TropicFull+TropicFullRainbow)+(TropicOMZ+TropicOMZRainbow))/((SpringFull+SpringFullRainbow)+(SpringOMZ+SpringOMZRainbow))/((SummerFull+SummerFullRainbow)+(SummerOMZ+SummerOMZRainbow))/((WinterFull+WinterFullRainbow)+(WinterOMZ+WinterOMZRainbow))
# MapCombo                          
```

https://sape.inf.usi.ch/quick-reference/ggplot2/geom_polygon

```{r}
world_coordinatesRainbowSurface <- map_data("world") 
world_coordinatesRainbowDepth <- map_data("world") 

world_coordinatesRainbowSurface$nm <- c(400, 700)
world_coordinatesRainbowDepth$nm <- c(400, 550)

data_textSurface <- data.frame(label = c('Near~Surface~(180~µE)'))
data_textDepth <- data.frame(label = c('Deep~(30~µE)'))
```


```{r}
#Full
d=data.frame(x=c(400,700,700), y=c(100,100,200), t=c('a', 'a', 'a'), r=c(1,2,3))
ddepth=data.frame(x=c(400,700,700), y=c(160,160,260), t=c('a', 'a', 'a'), r=c(1,2,3))

RainbowSurface<-ggplot() +
  stat_wl_strip(aes(x = nm), ymin = 150, ymax = 200, alpha = 0.5, world_coordinatesRainbowSurface) +
  scale_fill_identity() +
  geom_polygon(data=d, mapping=aes(x=x, y=y, group=t), fill = "red", show.legend = F) +
  geom_ellipse(aes(x0 = 555, y0 = 143, a = 164, b = 40, angle = pi / 10), fill = "red", colour = "red") +
  #geom_ellipse(aes(x0 = 555, y0 = 143, a = 170, b = 40, angle = pi / 20), fill = "white", colour = "white") +
  coord_fixed() +
  scale_y_continuous(breaks=seq(100, 200, by = 50)) +
  coord_cartesian(ylim = c(70, 230)) +
  geom_text(data=data_textSurface, aes(x=650, y=230, label=label), size=5, parse=TRUE) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        axis.text = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank(),
        strip.background = element_rect(fill="white"),
        strip.text = element_text(size=14),
        legend.background = element_rect(fill="transparent"),
        legend.position = c(0.12,0.76),
        legend.text = element_text(size=14))
RainbowSurface


RainbowSurface1<-ggplot() +
  stat_wl_strip(aes(x = nm), ymin = 100, ymax = 200, alpha = 0.5, world_coordinatesRainbowSurface) +
  scale_fill_identity() +
  geom_polygon(data=d, mapping=aes(x=x, y=y, group=t), fill = "white", show.legend = F) +
  #geom_ellipse(aes(x0 = 555, y0 = 143, a = 164, b = 28, angle = pi / 10), fill = "white", colour = "white") +
  coord_fixed() +
  scale_y_continuous(breaks=seq(100, 200, by = 50)) +
  coord_cartesian(ylim = c(70, 230)) +
  geom_text(data=data_textDepth, aes(x=650, y=230, label=label), size=5, parse=TRUE) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        axis.text = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank(),
        strip.background = element_rect(fill="white"),
        strip.text = element_text(size=14),
        legend.background = element_rect(fill="transparent"),
        legend.position = c(0.12,0.76),
        legend.text = element_text(size=14))
RainbowSurface1



RainbowDepth1<-ggplot() +
  stat_wl_strip(aes(x = nm), ymin = 180, ymax = 200, alpha = 0.5, world_coordinatesRainbowDepth) +
  scale_fill_identity() +
  geom_polygon(data=ddepth, mapping=aes(x=x, y=y, group=t), fill = "white", show.legend = F) +
  #geom_ellipse(aes(x0 = 555, y0 = 143, a = 164, b = 28, angle = pi / 10), fill = "white", colour = "white") +
  #geom_ellipse(aes(x0 = 555, y0 = 143, a = 170, b = 40, angle = pi / 20), fill = "white", colour = "white") +
  coord_fixed() +
  scale_y_continuous(breaks=seq(100, 200, by = 50)) +
  coord_cartesian(ylim = c(70, 230)) +
  geom_text(data=data_textSurface, aes(x=650, y=230, label=label), size=5, parse=TRUE) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        axis.text = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank(),
        strip.background = element_rect(fill="white"),
        strip.text = element_text(size=14),
        legend.background = element_rect(fill="transparent"),
        legend.position = c(0.12,0.76),
        legend.text = element_text(size=14))
RainbowDepth1

```


```{r}
#Full combo
# world_coordinatesRainbow <- map_data("world")
# world_coordinatesRainbow$nm <- c(400, 700)
# 
# data_text1 <- data.frame(label = c('Near~surface~(180~µE~","~8~h):~Clade~HLI'))
# data_text2 <- data.frame(label = c('Near~surface~(180~µE~","~11~h):~Clade~HLI'))
# data_text3 <- data.frame(label = c('Near~surface~(180~µE~","~15~h):~Clade~HLI'))
# 
# data_text4 <- data.frame(label = c('Deep~(30~µE~","~4~h):~Clade~LLIV'))
# data_text5 <- data.frame(label = c('Deep~(30~µE~","~6~h):~Clades~HLI~","~LLII/III~","~LLIV'))
# data_text6 <- data.frame(label = c('Deep~(30~µE~","~7~h):~Clades~HLI~","~LLII/III~","~LLIV'))
# data_text7 <- data.frame(label = c('Deep~(30~µE~","~10~h):~Clades~HLI~","~LLII/III~","~LLIV'))
# 
# 
# d=data.frame(x=c(400,700,700), y=c(100,100,200), t=c('a', 'a', 'a'), r=c(1,2,3))
# RainbowComboFull<-ggplot() +
#   stat_wl_strip(aes(x = nm), ymin = 100, ymax = 200, alpha = 0.5, world_coordinatesRainbow) +
#   scale_fill_identity() +
#   geom_polygon(data=d, mapping=aes(x=x, y=y, group=t), fill = "white", show.legend = F) +
#   geom_ellipse(aes(x0 = 555, y0 = 143, a = 164, b = 28, angle = pi / 10), fill = "white", colour = "white") +
#   coord_fixed() +
#   scale_y_continuous(breaks=seq(100, 200, by = 50)) +
#   coord_cartesian(ylim = c(80, 220)) +
#   geom_text(data=data_text1, aes(x=510, y=215, label=label), size=4.5, parse=TRUE) +
#   geom_text(data=data_text2, aes(x=510, y=210, label=label), size=4.5, parse=TRUE) +
#   geom_text(data=data_text3, aes(x=510, y=205, label=label), size=4.5, parse=TRUE) +
#   
#   geom_text(data=data_text4, aes(x=530, y=90, label=label), size=4.5, parse=TRUE) +
#   geom_text(data=data_text5, aes(x=530, y=85, label=label), size=4.5, parse=TRUE) + 
#   geom_text(data=data_text6, aes(x=530, y=80, label=label), size=4.5, parse=TRUE) +
#   geom_text(data=data_text7, aes(x=530, y=75, label=label), size=4.5, parse=TRUE) +
#   theme_bw() +
#   theme(panel.grid.minor = element_blank(),
#         panel.grid.major = element_blank(),
#         axis.text = element_blank(),
#         axis.title = element_blank(),
#         axis.ticks = element_blank(),
#         strip.background = element_rect(fill="white"),
#         strip.text = element_text(size=14),
#         legend.background = element_rect(fill="transparent"),
#         legend.position = c(0.12,0.76),
#         legend.text = element_text(size=14))
# RainbowComboFull

```

```{r}
#OMZ
world_coordinatesRainbow <- map_data("world")
world_coordinatesRainbow$nm <- c(400, 700)

data_text1d <- data.frame(label = c('Near~surface~(180~µE~","~8~h):~Clades~HLI~","~LLII/III~","~LLIV'))
data_text2d <- data.frame(label = c('Near~surface~(180~µE~","~11~h):~Clades~HLI~","~LLIV'))
data_text3d <- data.frame(label = c('Near~surface~(180~µE~","~15~h):~Clades~HLI~","~LLIV'))

data_text4d <- data.frame(label = c('Deep~(30~µE~","~4~h):~Clades~LLII/III~","~LLIV'))
data_text5d <- data.frame(label = c('Deep~(30~µE~","~6~h):~Clades~LLII/III~","~LLIV'))
data_text6d <- data.frame(label = c('Deep~(30~µE~","~7~h):~Clades~LLII/III~","~LLIV'))
data_text7d <- data.frame(label = c('Deep~(30~µE~","~10~h):~Clades~HLI~","~LLII/III~","~LLIV'))
```


```{r}
#OMZ
d=data.frame(x=c(400,700,700), y=c(100,100,200), t=c('a', 'a', 'a'), r=c(1,2,3))
RainbowTropicOMZ<-ggplot() +
  stat_wl_strip(aes(x = nm), ymin = 100, ymax = 200, alpha = 0.5, world_coordinatesRainbow) +
  scale_fill_identity() +
  geom_polygon(data=d, mapping=aes(x=x, y=y, group=t), fill = "white", show.legend = F) +
  geom_ellipse(aes(x0 = 555, y0 = 143, a = 164, b = 28, angle = pi / 10), fill = "white", colour = "white") +
  coord_fixed() +
  scale_y_continuous(breaks=seq(100, 200, by = 50)) +
  coord_cartesian(ylim = c(70, 230)) +
    geom_text(data=data_textOMZ, aes(x=650, y=230, label=label), size=5, parse=TRUE) +
  geom_text(data=data_text2d, aes(x=400, y=210, label=label, hjust=0), size=4.5, parse=TRUE) +
  geom_text(data=data_text6d, aes(x=400, y=90, label=label, hjust=0), size=4.5, parse=TRUE) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        axis.text = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank(),
        strip.background = element_rect(fill="white"),
        strip.text = element_text(size=14),
        legend.background = element_rect(fill="transparent"),
        legend.position = c(0.12,0.76),
        legend.text = element_text(size=14))
RainbowTropicOMZ


RainbowWinterOMZ<-ggplot() +
  stat_wl_strip(aes(x = nm), ymin = 100, ymax = 200, alpha = 0.5, world_coordinatesRainbow) +
  scale_fill_identity() +
  geom_polygon(data=d, mapping=aes(x=x, y=y, group=t), fill = "white", show.legend = F) +
  geom_ellipse(aes(x0 = 555, y0 = 143, a = 164, b = 28, angle = pi / 10), fill = "white", colour = "white") +
  coord_fixed() +
  scale_y_continuous(breaks=seq(100, 200, by = 50)) +
  coord_cartesian(ylim = c(70, 230)) +
      geom_text(data=data_textOMZ, aes(x=650, y=230, label=label), size=5, parse=TRUE) +
  geom_text(data=data_text1d, aes(x=400, y=230, label=label, hjust=0), size=4.5, parse=TRUE) +
  geom_text(data=data_text2d, aes(x=400, y=220, label=label, hjust=0), size=4.5, parse=TRUE) +
  geom_text(data=data_text3d, aes(x=400, y=210, label=label, hjust=0), size=4.5, parse=TRUE) +
  geom_text(data=data_text4d, aes(x=400, y=90, label=label, hjust=0), size=4.5, parse=TRUE) +
  geom_text(data=data_text6d, aes(x=400, y=80, label=label, hjust=0), size=4.5, parse=TRUE) +
  geom_text(data=data_text7d, aes(x=400, y=70, label=label, hjust=0), size=4.5, parse=TRUE) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        axis.text = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank(),
        strip.background = element_rect(fill="white"),
        strip.text = element_text(size=14),
        legend.background = element_rect(fill="transparent"),
        legend.position = c(0.12,0.76),
        legend.text = element_text(size=14))
RainbowWinterOMZ


RainbowSpringOMZ<-ggplot() +
  stat_wl_strip(aes(x = nm), ymin = 100, ymax = 200, alpha = 0.5, world_coordinatesRainbow) +
  scale_fill_identity() +
  geom_polygon(data=d, mapping=aes(x=x, y=y, group=t), fill = "white", show.legend = F) +
  geom_ellipse(aes(x0 = 555, y0 = 143, a = 164, b = 28, angle = pi / 10), fill = "white", colour = "white") +
  coord_fixed() +
  scale_y_continuous(breaks=seq(100, 200, by = 50)) +
  coord_cartesian(ylim = c(70, 230)) +
      geom_text(data=data_textOMZ, aes(x=650, y=230, label=label), size=5, parse=TRUE) +
  geom_text(data=data_text2d, aes(x=400, y=210, label=label, hjust=0), size=4.5, parse=TRUE) +
  geom_text(data=data_text5d, aes(x=400, y=90, label=label, hjust=0), size=4.5, parse=TRUE) + 
  geom_text(data=data_text6d, aes(x=400, y=80, label=label, hjust=0), size=4.5, parse=TRUE) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        axis.text = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank(),
        strip.background = element_rect(fill="white"),
        strip.text = element_text(size=14),
        legend.background = element_rect(fill="transparent"),
        legend.position = c(0.12,0.76),
        legend.text = element_text(size=14))
RainbowSpringOMZ


RainbowSummerOMZ<-ggplot() +
  stat_wl_strip(aes(x = nm), ymin = 100, ymax = 200, alpha = 0.5, world_coordinatesRainbow) +
  scale_fill_identity() +
  geom_polygon(data=d, mapping=aes(x=x, y=y, group=t), fill = "white", show.legend = F) +
  geom_ellipse(aes(x0 = 555, y0 = 143, a = 164, b = 28, angle = pi / 10), fill = "white", colour = "white") +
  coord_fixed() +
  scale_y_continuous(breaks=seq(100, 200, by = 50)) +
  coord_cartesian(ylim = c(70, 230)) +
      geom_text(data=data_textOMZ, aes(x=650, y=230, label=label), size=5, parse=TRUE) +
  geom_text(data=data_text1d, aes(x=400, y=210, label=label, hjust=0), size=4.5, parse=TRUE) +
  geom_text(data=data_text2d, aes(x=400, y=220, label=label, hjust=0), size=4.5, parse=TRUE) +
  geom_text(data=data_text3d, aes(x=400, y=230, label=label, hjust=0), size=4.5, parse=TRUE) +
  
  geom_text(data=data_text4d, aes(x=400, y=70, label=label, hjust=0), size=4.5, parse=TRUE) +
  geom_text(data=data_text6d, aes(x=400, y=80, label=label, hjust=0), size=4.5, parse=TRUE) +
  geom_text(data=data_text7d, aes(x=400, y=90, label=label, hjust=0), size=4.5, parse=TRUE) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        axis.text = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank(),
        strip.background = element_rect(fill="white"),
        strip.text = element_text(size=14),
        legend.background = element_rect(fill="transparent"),
        legend.position = c(0.12,0.76),
        legend.text = element_text(size=14))
RainbowSummerOMZ


```




```{r}
#OMZ combo
# world_coordinatesRainbow <- map_data("world")
# world_coordinatesRainbow$nm <- c(400, 700)
# 
# data_text1d <- data.frame(label = c('Near~surface~(180~µE~","~8~h):~Clades~HLI~","~LLII/III~","~LLIV'))
# data_text2d <- data.frame(label = c('Near~surface~(180~µE~","~11~h):~Clades~HLI~","~LLIV'))
# data_text3d <- data.frame(label = c('Near~surface~(180~µE~","~15~h):~Clades~HLI~","~LLIV'))
# 
# data_text4d <- data.frame(label = c('Deep~(30~µE~","~4~h):~Clades~LLII/III~","~LLIV'))
# data_text5d <- data.frame(label = c('Deep~(30~µE~","~6~h):~Clades~LLII/III~","~LLIV'))
# data_text6d <- data.frame(label = c('Deep~(30~µE~","~7~h):~Clades~LLII/III~","~LLIV'))
# data_text7d <- data.frame(label = c('Deep~(30~µE~","~10~h):~Clades~HLI~","~LLII/III~","~LLIV'))
# 
# 
# d=data.frame(x=c(400,700,700), y=c(100,100,200), t=c('a', 'a', 'a'), r=c(1,2,3))
# RainbowComboOMZ<-ggplot() +
#   stat_wl_strip(aes(x = nm), ymin = 100, ymax = 200, alpha = 0.5, world_coordinatesRainbow) +
#   scale_fill_identity() +
#   geom_polygon(data=d, mapping=aes(x=x, y=y, group=t), fill = "white", show.legend = F) +
#   geom_ellipse(aes(x0 = 555, y0 = 143, a = 164, b = 28, angle = pi / 10), fill = "white", colour = "white") +
#   coord_fixed() +
#   scale_y_continuous(breaks=seq(100, 200, by = 50)) +
#   coord_cartesian(ylim = c(80, 220)) +
#   geom_text(data=data_text1d, aes(x=510, y=215, label=label), size=4.5, parse=TRUE) +
#   geom_text(data=data_text2d, aes(x=510, y=210, label=label), size=4.5, parse=TRUE) +
#   geom_text(data=data_text3d, aes(x=510, y=205, label=label), size=4.5, parse=TRUE) +
#   
#   geom_text(data=data_text4d, aes(x=530, y=90, label=label), size=4.5, parse=TRUE) +
#   geom_text(data=data_text5d, aes(x=530, y=85, label=label), size=4.5, parse=TRUE) + 
#   geom_text(data=data_text6d, aes(x=530, y=80, label=label), size=4.5, parse=TRUE) +
#   geom_text(data=data_text7d, aes(x=530, y=75, label=label), size=4.5, parse=TRUE) +
#   theme_bw() +
#   theme(panel.grid.minor = element_blank(),
#         panel.grid.major = element_blank(),
#         axis.text = element_blank(),
#         axis.title = element_blank(),
#         axis.ticks = element_blank(),
#         strip.background = element_rect(fill="white"),
#         strip.text = element_text(size=14),
#         legend.background = element_rect(fill="transparent"),
#         legend.position = c(0.12,0.76),
#         legend.text = element_text(size=14))
# RainbowComboOMZ

```

```{r, fig.height = 16, fig.width = 24}
OMZRainbow<- (TropicFull+RainbowTropicFull+RainbowTropicOMZ)/(WinterFull+RainbowWinterFull+RainbowWinterOMZ)/(SpringFull+RainbowSpringFull+RainbowSpringOMZ)/(SummerFull+RainbowSummerFull+RainbowSummerOMZ)
OMZRainbow
```
```{r save plot}
#ggsave(file = file.path(FigPath, paste("MapComboPro_yeah",".png",sep = "")), height=16, width= 24,  dpi = 300, limitsize = TRUE)
```


# Save rds for further analysis

```{r save rds}
# saveRDS(object = CultureCatalog, file = file.path("..", "Data", "ImportedData", "ImportedMetaData", "CultureCatalog.Rds"), compress = "xz")
```

------------------------------------------------------------------------------------------------------------------------

# Create map
https://www.geeksforgeeks.org/how-to-make-world-map-with-ggplot2-in-r/

```{r}
world_coordinates2 <- map_data("world") %>% 
  filter(! long > 180) 

world_coordinates2$facetsA <- '(A)~~~~All~year'
world_coordinates2$facetsB <- '(B)~~~~Winter~or~summer~solstice'
world_coordinates2$facetsC <- '(C)~~~~Vernal~equinox'
world_coordinates2$facetsD <- '(D)~~~~Summer~or~winter~solstice'


world_coordinates2$facetsPresent <- 'Present'
world_coordinates2$facetsFuture <- 'Future~scenario'

# data_textA <- data.frame(label = c('A'))
# data_textB <- data.frame(label = c('B'))
# data_textC <- data.frame(label = c('C'))
# data_textD <- data.frame(label = c('D'))
```


```{r create map plot, fig.height = 4, fig.width = 6, warning = FALSE}

d=data.frame(x1=c(-Inf), x2=c(Inf), y1=c(35), y2=c(55))
d2=data.frame(x1=c(-Inf), x2=c(Inf), y1=c(-35), y2=c(-55))
d3=data.frame(x1=c(-Inf), x2=c(Inf), y1=c(-Inf), y2=c(Inf))
d4=data.frame(x1=c(-Inf), x2=c(Inf), y1=c(-15), y2=c(15))
d5=data.frame(x1=c(-Inf), x2=c(Inf), y1=c(-40), y2=c(40))

data_textTropicFull <- data.frame(label = c('All~year'))
data_textTropicFull2 <- data.frame(label = c('12~h'))
data_textTropicFull3 <- data.frame(label = c('11/7~h'))

TropicFull<-ggplot() + 
  geom_rect(data=d3, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "lightskyblue1", color="lightskyblue3", alpha=1) +
  geom_rect(data=d4, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "khaki1", color="khaki2", alpha=0.8) +
  geom_hline(yintercept = 40, fill = "transparent", color="chartreuse4", linetype = "dashed", alpha=1, size = 1) +
  geom_hline(yintercept = -40, fill = "transparent", color="chartreuse4", linetype = "dashed", alpha=1, size = 1) +
  #geom_hline(yintercept = 60, fill = "white", color="white", linetype = "solid", alpha=1, size = 1) +
  geom_map(data = world_coordinates2, map = world_coordinates2, aes(long, lat, map_id = region), color = "gray50", fill = "gray50", size = 0.2) +
  # geom_text(data=data_textA, aes(x=180, y=120, label=label), size=7, parse=TRUE) +
  # geom_text(data=data_textTropicFull, aes(x=0, y=110, label=label), size=5, parse=TRUE) +
  geom_text(data=data_textTropicFull2, aes(x=-170, y=0, label=label), size=4.5, parse=TRUE) +
  geom_text(data=data_textTropicFull3, aes(x=170, y=0, label=label), size=4.5, parse=TRUE) +
  scale_y_continuous(breaks=seq(-90, 90, by = 45)) +
  coord_cartesian(ylim = c(-90, 120)) +
  labs(y = "Latitude", x = "Longitude") +
  ggh4x::facet_nested(rows = vars(facetsPresent), cols = vars(facetsA), labeller = label_parsed, switch = "y") +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        strip.placement = "outside",
        strip.switch.pad.grid = unit(0.5, "cm"),
        axis.text = element_text(size=14),
        axis.title = element_text(size=14),
        strip.background = element_rect(fill="white"),
        strip.text.x = element_text(size=18, hjust = 0),
        strip.text.y = element_text(size=18),
        axis.title.y = element_text(vjust = -15),
        #axis.title.x = element_text(margin=margin(t=10)),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.background = element_rect(fill="transparent"),
        legend.position = c(0.12,0.76),
        legend.key.height= unit(0.005, 'cm'),
        legend.spacing.x = unit(0.01, 'cm'),
        legend.text = element_text(size=14)) +
  coord_map("moll")  
TropicFull

data_textWinterFull <- data.frame(label = c('Winter~or~summer~solstice'))
data_textWinterFull2 <- data.frame(label = c('9~h'))
data_textWinterFull3 <- data.frame(label = c('16~h'))
data_textWinterFull4 <- data.frame(label = c('8/4~h'))
data_textWinterFull5 <- data.frame(label = c('15/10~h'))

WinterFull<-ggplot() + 
  geom_rect(data=d3, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "lightskyblue1", color="lightskyblue3", alpha=1) +
  geom_rect(data=d, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "khaki1", color="khaki2", alpha=0.8) +
  geom_rect(data=d2, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "khaki1", color="khaki2", alpha=0.8) +
    geom_rect(data=d4, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "khaki1", color="khaki2", alpha=0.8) +
  geom_hline(yintercept = 40, fill = "transparent", color="chartreuse4", linetype = "dashed", alpha=1, size = 1) +
  geom_hline(yintercept = -40, fill = "transparent", color="chartreuse4", linetype = "dashed", alpha=1, size = 1) +
  #geom_hline(yintercept = 60, fill = "white", color="white", linetype = "solid", alpha=1, size = 1) +
  geom_map(data = world_coordinates2, map = world_coordinates2, aes(long, lat, map_id = region), color = "gray50", fill = "gray50", size = 0.2) +
    # geom_text(data=data_textB, aes(x=180, y=120, label=label), size=7, parse=TRUE) +
    # geom_text(data=data_textWinterFull, aes(x=0, y=110, label=label), size=5, parse=TRUE) +
    geom_text(data=data_textWinterFull2, aes(x=-160, y=45, label=label), size=4.5, parse=TRUE) +
    geom_text(data=data_textWinterFull3, aes(x=-160, y=-45, label=label), size=4.5, parse=TRUE) +
    geom_text(data=data_textWinterFull4, aes(x=160, y=45, label=label), size=4.5, parse=TRUE) +
    geom_text(data=data_textWinterFull5, aes(x=160, y=-45, label=label), size=4.5, parse=TRUE) +
    geom_text(data=data_textTropicFull2, aes(x=-170, y=0, label=label), size=4.5, parse=TRUE) +
    geom_text(data=data_textTropicFull3, aes(x=170, y=0, label=label), size=4.5, parse=TRUE) +
  scale_y_continuous(breaks=seq(-90, 90, by = 45)) +
  coord_cartesian(ylim = c(-90, 120)) +
  labs(y = "Latitude", x = "Longitude") +
  ggh4x::facet_nested(rows = vars(facetsFuture), cols = vars(facetsB), labeller = label_parsed, switch = "y") +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        strip.placement = "outside",
        strip.switch.pad.grid = unit(0.5, "cm"),
        axis.text = element_text(size=14),
        axis.title = element_text(size=14),
        strip.background = element_rect(fill="white"),
        strip.text.x = element_text(size=18, hjust = 0),
        strip.text.y = element_text(size=18),
        axis.title.y = element_text(vjust = -15),
        #axis.title.x = element_text(margin=margin(t=10)),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.background = element_rect(fill="transparent"),
        legend.position = c(0.12,0.76),
        legend.key.height= unit(0.005, 'cm'),
        legend.spacing.x = unit(0.01, 'cm'),
        legend.text = element_text(size=14)) +
  coord_map("moll") 
WinterFull


data_textSpringFull <- data.frame(label = c('Vernal~equinox'))
data_textSpringFull2 <- data.frame(label = c('12~h'))
data_textSpringFull3 <- data.frame(label = c('12~h'))
data_textSpringFull4 <- data.frame(label = c('11/6~h'))
data_textSpringFull5 <- data.frame(label = c('11/6~h'))

SpringFull<-ggplot() + 
  geom_rect(data=d3, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "lightskyblue1", color="lightskyblue3", alpha=1) +
  geom_rect(data=d, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "khaki1", color="khaki2", alpha=0.8) +
  geom_rect(data=d2, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "khaki1", color="khaki2", alpha=0.8) +
  geom_rect(data=d4, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "khaki1", color="khaki2", alpha=0.8) +
  geom_hline(yintercept = 40, fill = "transparent", color="chartreuse4", linetype = "dashed", alpha=1, size = 1) +
  geom_hline(yintercept = -40, fill = "transparent", color="chartreuse4", linetype = "dashed", alpha=1, size = 1) +
  #geom_hline(yintercept = 60, fill = "white", color="white", linetype = "solid", alpha=1, size = 1) +
  geom_map(data = world_coordinates2, map = world_coordinates2, aes(long, lat, map_id = region), color = "gray50", fill = "gray50", size = 0.2) +
    # geom_text(data=data_textC, aes(x=180, y=120, label=label), size=7, parse=TRUE) +
    # geom_text(data=data_textSpringFull, aes(x=0, y=110, label=label), size=5, parse=TRUE) +
    geom_text(data=data_textSpringFull2, aes(x=-160, y=45, label=label), size=4.5, parse=TRUE) +
    geom_text(data=data_textSpringFull3, aes(x=-160, y=-45, label=label), size=4.5, parse=TRUE) +
    geom_text(data=data_textSpringFull4, aes(x=160, y=45, label=label), size=4.5, parse=TRUE) +
    geom_text(data=data_textSpringFull5, aes(x=160, y=-45, label=label), size=4.5, parse=TRUE) +
    geom_text(data=data_textTropicFull2, aes(x=-170, y=0, label=label), size=4.5, parse=TRUE) +
    geom_text(data=data_textTropicFull3, aes(x=170, y=0, label=label), size=4.5, parse=TRUE) +
  scale_y_continuous(breaks=seq(-90, 90, by = 45)) +
  coord_cartesian(ylim = c(-90, 120)) +
  labs(y = "Latitude", x = "Longitude") +
  ggh4x::facet_nested(rows = vars(facetsFuture), cols = vars(facetsC), labeller = label_parsed, switch = "y") +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        strip.placement = "outside",
        strip.switch.pad.grid = unit(0.5, "cm"),
        axis.text = element_text(size=14),
        axis.title = element_text(size=14),
        strip.background = element_rect(fill="white"),
        strip.text.x = element_text(size=18, hjust = 0),
        strip.text.y = element_text(size=18),
        axis.title.y = element_text(vjust = -15),
        #axis.title.x = element_text(margin=margin(t=10)),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.background = element_rect(fill="transparent"),
        legend.position = c(0.12,0.76),
        legend.key.height= unit(0.005, 'cm'),
        legend.spacing.x = unit(0.01, 'cm'),
        legend.text = element_text(size=14)) +
  coord_map("moll") 
SpringFull

data_textSummerFull <- data.frame(label = c('Summer~or~winter~solstice'))
data_textSummerFull2 <- data.frame(label = c('16~h'))
data_textSummerFull3 <- data.frame(label = c('9~h'))
data_textSummerFull4 <- data.frame(label = c('15/10~h'))
data_textSummerFull5 <- data.frame(label = c('8/4~h'))
SummerFull<-ggplot() + 
  geom_rect(data=d3, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "lightskyblue1", color="lightskyblue3", alpha=1) +
  geom_rect(data=d, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "khaki1", color="khaki2", alpha=0.8) +
  geom_rect(data=d2, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "khaki1", color="khaki2", alpha=0.8) +
    geom_rect(data=d4, mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2), fill = "khaki1", color="khaki2", alpha=0.8) +
  geom_hline(yintercept = 40, fill = "transparent", color="chartreuse4", linetype = "dashed", alpha=1, size = 1) +
  geom_hline(yintercept = -40, fill = "transparent", color="chartreuse4", linetype = "dashed", alpha=1, size = 1) +
  #geom_hline(yintercept = 60, fill = "white", color="white", linetype = "solid", alpha=1, size = 1) +
  geom_map(data = world_coordinates2, map = world_coordinates2, aes(long, lat, map_id = region), color = "gray50", fill = "gray50", size = 0.2) +
    # geom_text(data=data_textD, aes(x=180, y=120, label=label), size=7, parse=TRUE) +
    # geom_text(data=data_textSummerFull, aes(x=0, y=110, label=label), size=5, parse=TRUE) +
    geom_text(data=data_textSummerFull2, aes(x=-160, y=45, label=label), size=4.5, parse=TRUE) +
    geom_text(data=data_textSummerFull3, aes(x=-160, y=-45, label=label), size=4.5, parse=TRUE) +
    geom_text(data=data_textSummerFull4, aes(x=160, y=45, label=label), size=4.5, parse=TRUE) +
    geom_text(data=data_textSummerFull5, aes(x=160, y=-45, label=label), size=4.5, parse=TRUE) +
      geom_text(data=data_textTropicFull2, aes(x=-170, y=0, label=label), size=4.5, parse=TRUE) +
      geom_text(data=data_textTropicFull3, aes(x=170, y=0, label=label), size=4.5, parse=TRUE) +
  scale_y_continuous(breaks=seq(-90, 90, by = 45)) +
  coord_cartesian(ylim = c(-90, 120)) +
  labs(y = "Latitude", x = "Longitude") +
  ggh4x::facet_nested(rows = vars(facetsFuture), cols = vars(facetsD), labeller = label_parsed, switch = "y") +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        strip.placement = "outside",
        strip.switch.pad.grid = unit(0.5, "cm"),
        axis.text = element_text(size=14),
        axis.title = element_text(size=14),
        strip.background = element_rect(fill="white"),
        strip.text.x = element_text(size=18, hjust = 0),
        strip.text.y = element_text(size=18),
        axis.title.y = element_text(vjust = -15),
        #axis.title.x = element_text(margin=margin(t=10)),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.background = element_rect(fill="transparent"),
        legend.position = c(0.12,0.76),
        legend.key.height= unit(0.005, 'cm'),
        legend.spacing.x = unit(0.01, 'cm'),
        legend.text = element_text(size=14)) +
  coord_map("moll") 
SummerFull



```


```{r}
#FUll
world_coordinatesRainbow <- map_data("world")
world_coordinatesRainbow$nm <- c(400, 700)

world_coordinatesRainbow$facetsFull <- '~~~~Oxygen:~Full'
world_coordinatesRainbow$facetsOMZ <- '~~~~Oxygen:~OMZ'

data_text1 <- data.frame(label = c('Near~surface~"~10m"~(180~µE~","~8~h):~Clade~HLI'))
data_text2 <- data.frame(label = c('Near~surface~"~10m"~(180~µE~","~11~h):~Clade~HLI'))
data_text3 <- data.frame(label = c('Near~surface~"~10m"~(180~µE~","~15~h):~Clade~HLI'))

data_text4 <- data.frame(label = c('Deep~"~100m"~(30~µE~","~4~h):~Clade~LLIV'))
data_text5 <- data.frame(label = c('Deep~"~100m"~(30~µE~","~6~h):~Clades~HLI~","~LLII/III~","~LLIV'))
data_text6 <- data.frame(label = c('Deep~"~100m"~(30~µE~","~7~h):~Clades~HLI~","~LLII/III~","~LLIV'))
data_text7 <- data.frame(label = c('Deep~"~100m"~(30~µE~","~10~h):~Clades~HLI~","~LLII/III~","~LLIV'))

data_text1d <- data.frame(label = c('Near~surface~"~10m"~(180~µE~","~8~h):~Clades~HLI~","~LLII/III~","~LLIV'))
data_text2d <- data.frame(label = c('Near~surface~"~10m"~(180~µE~","~11~h):~Clades~HLI~","~LLIV'))
data_text3d <- data.frame(label = c('Near~surface~"~10m"~(180~µE~","~15~h):~Clades~HLI~","~LLIV'))

data_text4d <- data.frame(label = c('Deep~"~100m"~(30~µE~","~4~h):~Clades~LLII/III~","~LLIV'))
data_text5d <- data.frame(label = c('Deep~"~100m"~(30~µE~","~6~h):~Clades~LLII/III~","~LLIV'))
data_text6d <- data.frame(label = c('Deep~"~100m"~(30~µE~","~7~h):~Clades~LLII/III~","~LLIV'))
data_text7d <- data.frame(label = c('Deep~"~100m"~(30~µE~","~10~h):~Clades~HLI~","~LLII/III~","~LLIV'))


data_textFull <- data.frame(label = c('Oxygen:~Full'))
data_textOMZ <- data.frame(label = c('Oxygen:~OMZ'))
```


```{r}
#Full
d=data.frame(x=c(400,700,700), y=c(100,100,200), t=c('a', 'a', 'a'), r=c(1,2,3))
RainbowTropicFull<-ggplot() +
  stat_wl_strip(aes(x = nm), ymin = 100, ymax = 200, alpha = 0.5, world_coordinatesRainbow) +
  scale_fill_identity() +
  geom_polygon(data=d, mapping=aes(x=x, y=y, group=t), fill = "white", show.legend = F) +
  geom_ellipse(aes(x0 = 555, y0 = 143, a = 164, b = 28, angle = pi / 10), fill = "white", colour = "white") +
  coord_fixed() +
  scale_y_continuous(breaks=seq(100, 200, by = 50)) +
  coord_cartesian(ylim = c(70, 230)) +
  #geom_text(data=data_textFull, aes(x=650, y=230, label=label), size=5, parse=TRUE) +
  geom_text(data=data_text2, aes(x=400, y=210, label=label, hjust=0), size=4.5, parse=TRUE) +
  geom_text(data=data_text6, aes(x=400, y=90, label=label, hjust=0), size=4.5, parse=TRUE) +
  ggh4x::facet_nested(cols = vars(facetsFull), labeller = label_parsed) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        strip.placement = "outside",
        strip.switch.pad.grid = unit(0.5, "cm"),
        strip.background = element_rect(fill="white"),
        strip.text.x = element_text(size=18, hjust = 0),
        strip.text.y = element_text(size=18),
        #axis.title.y = element_text(vjust = -15),
        #axis.title.x = element_text(margin=margin(t=10)),
        axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.background = element_rect(fill="transparent"),
        legend.position = c(0.12,0.76),
        legend.key.height= unit(0.005, 'cm'),
        legend.spacing.x = unit(0.01, 'cm'),
        legend.text = element_text(size=14)) 
RainbowTropicFull


RainbowWinterFull<-ggplot() +
  stat_wl_strip(aes(x = nm), ymin = 100, ymax = 200, alpha = 0.5, world_coordinatesRainbow) +
  scale_fill_identity() +
  geom_polygon(data=d, mapping=aes(x=x, y=y, group=t), fill = "white", show.legend = F) +
  geom_ellipse(aes(x0 = 555, y0 = 143, a = 164, b = 28, angle = pi / 10), fill = "white", colour = "white") +
  coord_fixed() +
  scale_y_continuous(breaks=seq(100, 200, by = 50)) +
  coord_cartesian(ylim = c(70, 230)) +
    #geom_text(data=data_textFull, aes(x=650, y=230, label=label), size=5, parse=TRUE) +
  geom_text(data=data_text1, aes(x=400, y=230, label=label, hjust=0), size=4.5, parse=TRUE) +
  geom_text(data=data_text2, aes(x=400, y=220, label=label, hjust=0), size=4.5, parse=TRUE) +
  geom_text(data=data_text3, aes(x=400, y=210, label=label, hjust=0), size=4.5, parse=TRUE) +
  geom_text(data=data_text4, aes(x=400, y=90, label=label, hjust=0), size=4.5, parse=TRUE) +
  geom_text(data=data_text6, aes(x=400, y=80, label=label, hjust=0), size=4.5, parse=TRUE) +
  geom_text(data=data_text7, aes(x=400, y=70, label=label, hjust=0), size=4.5, parse=TRUE) +
    ggh4x::facet_nested(cols = vars(facetsFull), labeller = label_parsed) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        strip.placement = "outside",
        strip.switch.pad.grid = unit(0.5, "cm"),
        strip.background = element_rect(fill="white"),
        strip.text.x = element_text(size=18, hjust = 0),
        strip.text.y = element_text(size=18),
        #axis.title.y = element_text(vjust = -15),
        #axis.title.x = element_text(margin=margin(t=10)),
        axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.background = element_rect(fill="transparent"),
        legend.position = c(0.12,0.76),
        legend.key.height= unit(0.005, 'cm'),
        legend.spacing.x = unit(0.01, 'cm'),
        legend.text = element_text(size=14)) 
RainbowWinterFull


RainbowSpringFull<-ggplot() +
  stat_wl_strip(aes(x = nm), ymin = 100, ymax = 200, alpha = 0.5, world_coordinatesRainbow) +
  scale_fill_identity() +
  geom_polygon(data=d, mapping=aes(x=x, y=y, group=t), fill = "white", show.legend = F) +
  geom_ellipse(aes(x0 = 555, y0 = 143, a = 164, b = 28, angle = pi / 10), fill = "white", colour = "white") +
  coord_fixed() +
  scale_y_continuous(breaks=seq(100, 200, by = 50)) +
  coord_cartesian(ylim = c(70, 230)) +
    #geom_text(data=data_textFull, aes(x=650, y=230, label=label), size=5, parse=TRUE) +
  geom_text(data=data_text2, aes(x=400, y=210, label=label, hjust=0), size=4.5, parse=TRUE) +
  geom_text(data=data_text5, aes(x=400, y=90, label=label, hjust=0), size=4.5, parse=TRUE) + 
  geom_text(data=data_text6, aes(x=400, y=80, label=label, hjust=0), size=4.5, parse=TRUE) +
    ggh4x::facet_nested(cols = vars(facetsFull), labeller = label_parsed) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        strip.placement = "outside",
        strip.switch.pad.grid = unit(0.5, "cm"),
        strip.background = element_rect(fill="white"),
        strip.text.x = element_text(size=18, hjust = 0),
        strip.text.y = element_text(size=18),
        #axis.title.y = element_text(vjust = -15),
        #axis.title.x = element_text(margin=margin(t=10)),
        axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.background = element_rect(fill="transparent"),
        legend.position = c(0.12,0.76),
        legend.key.height= unit(0.005, 'cm'),
        legend.spacing.x = unit(0.01, 'cm'),
        legend.text = element_text(size=14)) 
RainbowSpringFull


RainbowSummerFull<-ggplot() +
  stat_wl_strip(aes(x = nm), ymin = 100, ymax = 200, alpha = 0.5, world_coordinatesRainbow) +
  scale_fill_identity() +
  geom_polygon(data=d, mapping=aes(x=x, y=y, group=t), fill = "white", show.legend = F) +
  geom_ellipse(aes(x0 = 555, y0 = 143, a = 164, b = 28, angle = pi / 10), fill = "white", colour = "white") +
  coord_fixed() +
  scale_y_continuous(breaks=seq(100, 200, by = 50)) +
  coord_cartesian(ylim = c(70, 230)) +
    #geom_text(data=data_textFull, aes(x=650, y=230, label=label), size=5, parse=TRUE) +
  geom_text(data=data_text1, aes(x=400, y=210, label=label, hjust=0), size=4.5, parse=TRUE) +
  geom_text(data=data_text2, aes(x=400, y=220, label=label, hjust=0), size=4.5, parse=TRUE) +
  geom_text(data=data_text3, aes(x=400, y=230, label=label, hjust=0), size=4.5, parse=TRUE) +
  
  geom_text(data=data_text4, aes(x=400, y=70, label=label, hjust=0), size=4.5, parse=TRUE) +
  geom_text(data=data_text6, aes(x=400, y=80, label=label, hjust=0), size=4.5, parse=TRUE) +
  geom_text(data=data_text7, aes(x=400, y=90, label=label, hjust=0), size=4.5, parse=TRUE) +
    ggh4x::facet_nested(cols = vars(facetsFull), labeller = label_parsed) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        strip.placement = "outside",
        strip.switch.pad.grid = unit(0.5, "cm"),
        strip.background = element_rect(fill="white"),
        strip.text.x = element_text(size=18, hjust = 0),
        strip.text.y = element_text(size=18),
        #axis.title.y = element_text(vjust = -15),
        #axis.title.x = element_text(margin=margin(t=10)),
        axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.background = element_rect(fill="transparent"),
        legend.position = c(0.12,0.76),
        legend.key.height= unit(0.005, 'cm'),
        legend.spacing.x = unit(0.01, 'cm'),
        legend.text = element_text(size=14)) 
RainbowSummerFull

```



```{r}
#OMZ
d=data.frame(x=c(400,700,700), y=c(100,100,200), t=c('a', 'a', 'a'), r=c(1,2,3))
RainbowTropicOMZ<-ggplot() +
  stat_wl_strip(aes(x = nm), ymin = 100, ymax = 200, alpha = 0.5, world_coordinatesRainbow) +
  scale_fill_identity() +
  geom_polygon(data=d, mapping=aes(x=x, y=y, group=t), fill = "white", show.legend = F) +
  geom_ellipse(aes(x0 = 555, y0 = 143, a = 164, b = 28, angle = pi / 10), fill = "white", colour = "white") +
  coord_fixed() +
  scale_y_continuous(breaks=seq(100, 200, by = 50)) +
  coord_cartesian(ylim = c(70, 230)) +
    #geom_text(data=data_textOMZ, aes(x=650, y=230, label=label), size=5, parse=TRUE) +
  geom_text(data=data_text2d, aes(x=400, y=210, label=label, hjust=0), size=4.5, parse=TRUE) +
  geom_text(data=data_text6d, aes(x=400, y=90, label=label, hjust=0), size=4.5, parse=TRUE) +
    ggh4x::facet_nested(cols = vars(facetsOMZ), labeller = label_parsed) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        strip.placement = "outside",
        strip.switch.pad.grid = unit(0.5, "cm"),
        strip.background = element_rect(fill="white"),
        strip.text.x = element_text(size=18, hjust = 0),
        strip.text.y = element_text(size=18),
        #axis.title.y = element_text(vjust = -15),
        #axis.title.x = element_text(margin=margin(t=10)),
        axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.background = element_rect(fill="transparent"),
        legend.position = c(0.12,0.76),
        legend.key.height= unit(0.005, 'cm'),
        legend.spacing.x = unit(0.01, 'cm'),
        legend.text = element_text(size=14)) 
RainbowTropicOMZ


RainbowWinterOMZ<-ggplot() +
  stat_wl_strip(aes(x = nm), ymin = 100, ymax = 200, alpha = 0.5, world_coordinatesRainbow) +
  scale_fill_identity() +
  geom_polygon(data=d, mapping=aes(x=x, y=y, group=t), fill = "white", show.legend = F) +
  geom_ellipse(aes(x0 = 555, y0 = 143, a = 164, b = 28, angle = pi / 10), fill = "white", colour = "white") +
  coord_fixed() +
  scale_y_continuous(breaks=seq(100, 200, by = 50)) +
  coord_cartesian(ylim = c(70, 230)) +
      #geom_text(data=data_textOMZ, aes(x=650, y=230, label=label), size=5, parse=TRUE) +
  geom_text(data=data_text1d, aes(x=400, y=230, label=label, hjust=0), size=4.5, parse=TRUE) +
  geom_text(data=data_text2d, aes(x=400, y=220, label=label, hjust=0), size=4.5, parse=TRUE) +
  geom_text(data=data_text3d, aes(x=400, y=210, label=label, hjust=0), size=4.5, parse=TRUE) +
  geom_text(data=data_text4d, aes(x=400, y=90, label=label, hjust=0), size=4.5, parse=TRUE) +
  geom_text(data=data_text6d, aes(x=400, y=80, label=label, hjust=0), size=4.5, parse=TRUE) +
  geom_text(data=data_text7d, aes(x=400, y=70, label=label, hjust=0), size=4.5, parse=TRUE) +
      ggh4x::facet_nested(cols = vars(facetsOMZ), labeller = label_parsed) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        strip.placement = "outside",
        strip.switch.pad.grid = unit(0.5, "cm"),
        strip.background = element_rect(fill="white"),
        strip.text.x = element_text(size=18, hjust = 0),
        strip.text.y = element_text(size=18),
        #axis.title.y = element_text(vjust = -15),
        #axis.title.x = element_text(margin=margin(t=10)),
        axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.background = element_rect(fill="transparent"),
        legend.position = c(0.12,0.76),
        legend.key.height= unit(0.005, 'cm'),
        legend.spacing.x = unit(0.01, 'cm'),
        legend.text = element_text(size=14)) 
RainbowWinterOMZ


RainbowSpringOMZ<-ggplot() +
  stat_wl_strip(aes(x = nm), ymin = 100, ymax = 200, alpha = 0.5, world_coordinatesRainbow) +
  scale_fill_identity() +
  geom_polygon(data=d, mapping=aes(x=x, y=y, group=t), fill = "white", show.legend = F) +
  geom_ellipse(aes(x0 = 555, y0 = 143, a = 164, b = 28, angle = pi / 10), fill = "white", colour = "white") +
  coord_fixed() +
  scale_y_continuous(breaks=seq(100, 200, by = 50)) +
  coord_cartesian(ylim = c(70, 230)) +
      #geom_text(data=data_textOMZ, aes(x=650, y=230, label=label), size=5, parse=TRUE) +
  geom_text(data=data_text2d, aes(x=400, y=210, label=label, hjust=0), size=4.5, parse=TRUE) +
  geom_text(data=data_text5d, aes(x=400, y=90, label=label, hjust=0), size=4.5, parse=TRUE) + 
  geom_text(data=data_text6d, aes(x=400, y=80, label=label, hjust=0), size=4.5, parse=TRUE) +
      ggh4x::facet_nested(cols = vars(facetsOMZ), labeller = label_parsed) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        strip.placement = "outside",
        strip.switch.pad.grid = unit(0.5, "cm"),
        strip.background = element_rect(fill="white"),
        strip.text.x = element_text(size=18, hjust = 0),
        strip.text.y = element_text(size=18),
        #axis.title.y = element_text(vjust = -15),
        #axis.title.x = element_text(margin=margin(t=10)),
        axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.background = element_rect(fill="transparent"),
        legend.position = c(0.12,0.76),
        legend.key.height= unit(0.005, 'cm'),
        legend.spacing.x = unit(0.01, 'cm'),
        legend.text = element_text(size=14)) 
RainbowSpringOMZ


RainbowSummerOMZ<-ggplot() +
  stat_wl_strip(aes(x = nm), ymin = 100, ymax = 200, alpha = 0.5, world_coordinatesRainbow) +
  scale_fill_identity() +
  geom_polygon(data=d, mapping=aes(x=x, y=y, group=t), fill = "white", show.legend = F) +
  geom_ellipse(aes(x0 = 555, y0 = 143, a = 164, b = 28, angle = pi / 10), fill = "white", colour = "white") +
  coord_fixed() +
  scale_y_continuous(breaks=seq(100, 200, by = 50)) +
  coord_cartesian(ylim = c(70, 230)) +
      #geom_text(data=data_textOMZ, aes(x=650, y=230, label=label), size=5, parse=TRUE) +
  geom_text(data=data_text1d, aes(x=400, y=210, label=label, hjust=0), size=4.5, parse=TRUE) +
  geom_text(data=data_text2d, aes(x=400, y=220, label=label, hjust=0), size=4.5, parse=TRUE) +
  geom_text(data=data_text3d, aes(x=400, y=230, label=label, hjust=0), size=4.5, parse=TRUE) +
  
  geom_text(data=data_text4d, aes(x=400, y=70, label=label, hjust=0), size=4.5, parse=TRUE) +
  geom_text(data=data_text6d, aes(x=400, y=80, label=label, hjust=0), size=4.5, parse=TRUE) +
  geom_text(data=data_text7d, aes(x=400, y=90, label=label, hjust=0), size=4.5, parse=TRUE) +
      ggh4x::facet_nested(cols = vars(facetsOMZ), labeller = label_parsed) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        strip.placement = "outside",
        strip.switch.pad.grid = unit(0.5, "cm"),
        strip.background = element_rect(fill="white"),
        strip.text.x = element_text(size=18, hjust = 0),
        strip.text.y = element_text(size=18),
        #axis.title.y = element_text(vjust = -15),
        #axis.title.x = element_text(margin=margin(t=10)),
        axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.background = element_rect(fill="transparent"),
        legend.position = c(0.12,0.76),
        legend.key.height= unit(0.005, 'cm'),
        legend.spacing.x = unit(0.01, 'cm'),
        legend.text = element_text(size=14)) 
RainbowSummerOMZ


```


```{r, fig.height = 16, fig.width = 24}
OMZRainbow2<- (TropicFull+RainbowTropicFull+RainbowTropicOMZ)/(WinterFull+RainbowWinterFull+RainbowWinterOMZ)/(SpringFull+RainbowSpringFull+RainbowSpringOMZ)/(SummerFull+RainbowSummerFull+RainbowSummerOMZ)
OMZRainbow2
```



















